package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class CommodityInformation extends CommodityInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.id
     *
     * @return the value of tbl_commodity_information.id
     *
     * @mbggenerated
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.subordinate_departments
     *
     * @mbggenerated
     */
    private String subordinateDepartments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.affiliated_company
     *
     * @mbggenerated
     */
    private String affiliatedCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_name
     *
     * @mbggenerated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_abbreviation
     *
     * @mbggenerated
     */
    private String commodityAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_mn
     *
     * @mbggenerated
     */
    private String commodityMn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_specs
     *
     * @mbggenerated
     */
    private String commoditySpecs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_color
     *
     * @mbggenerated
     */
    private String commodityColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_attribute
     *
     * @mbggenerated
     */
    private String commodityAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_bar_code
     *
     * @mbggenerated
     */
    private String commodityBarCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.supplier_phone
     *
     * @mbggenerated
     */
    private String supplierPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.supplier_code
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_brand
     *
     * @mbggenerated
     */
    private String commodityBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_category
     *
     * @mbggenerated
     */
    private String commodityCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_subgroup
     *
     * @mbggenerated
     */
    private String commoditySubgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.storage_temperature
     *
     * @mbggenerated
     */
    private String storageTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.removable
     *
     * @mbggenerated
     */
    private Integer removable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.encoder_number
     *
     * @mbggenerated
     */
    private Integer encoderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.encoder_height
     *
     * @mbggenerated
     */
    private Integer encoderHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.production_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date productionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.qgp
     *
     * @mbggenerated
     */
    private Integer qgp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commdity_images
     *
     * @mbggenerated
     */
    private String commdityImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.disassemble_number
     *
     * @mbggenerated
     */
    private Long disassembleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.number_volume_ratio
     *
     * @mbggenerated
     */
    private Double numberVolumeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.number_gw_ratio
     *
     * @mbggenerated
     */
    private Double numberGwRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.number_nw_ratio
     *
     * @mbggenerated
     */
    private Double numberNwRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.dimension_unit
     *
     * @mbggenerated
     */
    private String dimensionUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.item_length
     *
     * @mbggenerated
     */
    private Double itemLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.item_wide
     *
     * @mbggenerated
     */
    private Double itemWide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.item_high
     *
     * @mbggenerated
     */
    private Double itemHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.fcl_length
     *
     * @mbggenerated
     */
    private Double fclLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.fcl_wide
     *
     * @mbggenerated
     */
    private Double fclWide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.fcl_high
     *
     * @mbggenerated
     */
    private Double fclHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.single_volume
     *
     * @mbggenerated
     */
    private Double singleVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.total_volume
     *
     * @mbggenerated
     */
    private Double totalVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_remark
     *
     * @mbggenerated
     */
    private String commodityRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.gross_weight
     *
     * @mbggenerated
     */
    private Long grossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.net_weight
     *
     * @mbggenerated
     */
    private Long netWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_unit_price
     *
     * @mbggenerated
     */
    private BigDecimal commodityUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.storage_unit
     *
     * @mbggenerated
     */
    private Integer storageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_total_price
     *
     * @mbggenerated
     */
    private BigDecimal commodityTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_storage_type
     *
     * @mbggenerated
     */
    private Integer commodityStorageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.mass_unit
     *
     * @mbggenerated
     */
    private String massUnit;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.id
     *
     * @param id the value for tbl_commodity_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_id
     *
     * @return the value of tbl_commodity_information.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    @Override
    public String toString() {
        return "CommodityInformation{" +
                "id='" + id + '\'' +
                ", commodityId='" + commodityId + '\'' +
                ", createBy='" + createBy + '\'' +
                ", createDate=" + createDate +
                ", updateBy='" + updateBy + '\'' +
                ", updateDate=" + updateDate +
                ", subordinateDepartments='" + subordinateDepartments + '\'' +
                ", affiliatedCompany='" + affiliatedCompany + '\'' +
                ", commodityName='" + commodityName + '\'' +
                ", commodityAbbreviation='" + commodityAbbreviation + '\'' +
                ", commodityCode='" + commodityCode + '\'' +
                ", commodityMn='" + commodityMn + '\'' +
                ", commoditySpecs='" + commoditySpecs + '\'' +
                ", commodityColor='" + commodityColor + '\'' +
                ", commodityAttribute='" + commodityAttribute + '\'' +
                ", commodityBarCode='" + commodityBarCode + '\'' +
                ", supplierName='" + supplierName + '\'' +
                ", supplierId='" + supplierId + '\'' +
                ", supplierPhone='" + supplierPhone + '\'' +
                ", supplierCode='" + supplierCode + '\'' +
                ", commodityBrand='" + commodityBrand + '\'' +
                ", commodityCategory='" + commodityCategory + '\'' +
                ", commoditySubgroup='" + commoditySubgroup + '\'' +
                ", storageTemperature='" + storageTemperature + '\'' +
                ", removable=" + removable +
                ", encoderNumber=" + encoderNumber +
                ", encoderHeight=" + encoderHeight +
                ", productionDate=" + productionDate +
                ", qgp=" + qgp +
                ", commdityImages='" + commdityImages + '\'' +
                ", company='" + company + '\'' +
                ", disassembleNumber=" + disassembleNumber +
                ", numberVolumeRatio=" + numberVolumeRatio +
                ", numberGwRatio=" + numberGwRatio +
                ", numberNwRatio=" + numberNwRatio +
                ", dimensionUnit='" + dimensionUnit + '\'' +
                ", itemLength=" + itemLength +
                ", itemWide=" + itemWide +
                ", itemHigh=" + itemHigh +
                ", fclLength=" + fclLength +
                ", fclWide=" + fclWide +
                ", fclHigh=" + fclHigh +
                ", singleVolume=" + singleVolume +
                ", totalVolume=" + totalVolume +
                ", commodityRemark='" + commodityRemark + '\'' +
                ", status=" + status +
                ", grossWeight=" + grossWeight +
                ", netWeight=" + netWeight +
                ", commodityUnitPrice=" + commodityUnitPrice +
                ", storageUnit=" + storageUnit +
                ", commodityTotalPrice=" + commodityTotalPrice +
                ", commodityStorageType=" + commodityStorageType +
                ", massUnit='" + massUnit + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_id
     *
     * @param commodityId the value for tbl_commodity_information.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.create_by
     *
     * @return the value of tbl_commodity_information.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.create_by
     *
     * @param createBy the value for tbl_commodity_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.create_date
     *
     * @return the value of tbl_commodity_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.create_date
     *
     * @param createDate the value for tbl_commodity_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.update_by
     *
     * @return the value of tbl_commodity_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.update_by
     *
     * @param updateBy the value for tbl_commodity_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.update_date
     *
     * @return the value of tbl_commodity_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.update_date
     *
     * @param updateDate the value for tbl_commodity_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.subordinate_departments
     *
     * @return the value of tbl_commodity_information.subordinate_departments
     *
     * @mbggenerated
     */
    public String getSubordinateDepartments() {
        return subordinateDepartments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.subordinate_departments
     *
     * @param subordinateDepartments the value for tbl_commodity_information.subordinate_departments
     *
     * @mbggenerated
     */
    public void setSubordinateDepartments(String subordinateDepartments) {
        this.subordinateDepartments = subordinateDepartments == null ? null : subordinateDepartments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.affiliated_company
     *
     * @return the value of tbl_commodity_information.affiliated_company
     *
     * @mbggenerated
     */
    public String getAffiliatedCompany() {
        return affiliatedCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.affiliated_company
     *
     * @param affiliatedCompany the value for tbl_commodity_information.affiliated_company
     *
     * @mbggenerated
     */
    public void setAffiliatedCompany(String affiliatedCompany) {
        this.affiliatedCompany = affiliatedCompany == null ? null : affiliatedCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_name
     *
     * @return the value of tbl_commodity_information.commodity_name
     *
     * @mbggenerated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_name
     *
     * @param commodityName the value for tbl_commodity_information.commodity_name
     *
     * @mbggenerated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_abbreviation
     *
     * @return the value of tbl_commodity_information.commodity_abbreviation
     *
     * @mbggenerated
     */
    public String getCommodityAbbreviation() {
        return commodityAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_abbreviation
     *
     * @param commodityAbbreviation the value for tbl_commodity_information.commodity_abbreviation
     *
     * @mbggenerated
     */
    public void setCommodityAbbreviation(String commodityAbbreviation) {
        this.commodityAbbreviation = commodityAbbreviation == null ? null : commodityAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_code
     *
     * @return the value of tbl_commodity_information.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_code
     *
     * @param commodityCode the value for tbl_commodity_information.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_mn
     *
     * @return the value of tbl_commodity_information.commodity_mn
     *
     * @mbggenerated
     */
    public String getCommodityMn() {
        return commodityMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_mn
     *
     * @param commodityMn the value for tbl_commodity_information.commodity_mn
     *
     * @mbggenerated
     */
    public void setCommodityMn(String commodityMn) {
        this.commodityMn = commodityMn == null ? null : commodityMn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_specs
     *
     * @return the value of tbl_commodity_information.commodity_specs
     *
     * @mbggenerated
     */
    public String getCommoditySpecs() {
        return commoditySpecs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_specs
     *
     * @param commoditySpecs the value for tbl_commodity_information.commodity_specs
     *
     * @mbggenerated
     */
    public void setCommoditySpecs(String commoditySpecs) {
        this.commoditySpecs = commoditySpecs == null ? null : commoditySpecs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_color
     *
     * @return the value of tbl_commodity_information.commodity_color
     *
     * @mbggenerated
     */
    public String getCommodityColor() {
        return commodityColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_color
     *
     * @param commodityColor the value for tbl_commodity_information.commodity_color
     *
     * @mbggenerated
     */
    public void setCommodityColor(String commodityColor) {
        this.commodityColor = commodityColor == null ? null : commodityColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_attribute
     *
     * @return the value of tbl_commodity_information.commodity_attribute
     *
     * @mbggenerated
     */
    public String getCommodityAttribute() {
        return commodityAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_attribute
     *
     * @param commodityAttribute the value for tbl_commodity_information.commodity_attribute
     *
     * @mbggenerated
     */
    public void setCommodityAttribute(String commodityAttribute) {
        this.commodityAttribute = commodityAttribute == null ? null : commodityAttribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_bar_code
     *
     * @return the value of tbl_commodity_information.commodity_bar_code
     *
     * @mbggenerated
     */
    public String getCommodityBarCode() {
        return commodityBarCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_bar_code
     *
     * @param commodityBarCode the value for tbl_commodity_information.commodity_bar_code
     *
     * @mbggenerated
     */
    public void setCommodityBarCode(String commodityBarCode) {
        this.commodityBarCode = commodityBarCode == null ? null : commodityBarCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.supplier_name
     *
     * @return the value of tbl_commodity_information.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.supplier_name
     *
     * @param supplierName the value for tbl_commodity_information.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.supplier_id
     *
     * @return the value of tbl_commodity_information.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.supplier_id
     *
     * @param supplierId the value for tbl_commodity_information.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.supplier_phone
     *
     * @return the value of tbl_commodity_information.supplier_phone
     *
     * @mbggenerated
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.supplier_phone
     *
     * @param supplierPhone the value for tbl_commodity_information.supplier_phone
     *
     * @mbggenerated
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.supplier_code
     *
     * @return the value of tbl_commodity_information.supplier_code
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.supplier_code
     *
     * @param supplierCode the value for tbl_commodity_information.supplier_code
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_brand
     *
     * @return the value of tbl_commodity_information.commodity_brand
     *
     * @mbggenerated
     */
    public String getCommodityBrand() {
        return commodityBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_brand
     *
     * @param commodityBrand the value for tbl_commodity_information.commodity_brand
     *
     * @mbggenerated
     */
    public void setCommodityBrand(String commodityBrand) {
        this.commodityBrand = commodityBrand == null ? null : commodityBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_category
     *
     * @return the value of tbl_commodity_information.commodity_category
     *
     * @mbggenerated
     */
    public String getCommodityCategory() {
        return commodityCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_category
     *
     * @param commodityCategory the value for tbl_commodity_information.commodity_category
     *
     * @mbggenerated
     */
    public void setCommodityCategory(String commodityCategory) {
        this.commodityCategory = commodityCategory == null ? null : commodityCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_subgroup
     *
     * @return the value of tbl_commodity_information.commodity_subgroup
     *
     * @mbggenerated
     */
    public String getCommoditySubgroup() {
        return commoditySubgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_subgroup
     *
     * @param commoditySubgroup the value for tbl_commodity_information.commodity_subgroup
     *
     * @mbggenerated
     */
    public void setCommoditySubgroup(String commoditySubgroup) {
        this.commoditySubgroup = commoditySubgroup == null ? null : commoditySubgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.storage_temperature
     *
     * @return the value of tbl_commodity_information.storage_temperature
     *
     * @mbggenerated
     */
    public String getStorageTemperature() {
        return storageTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.storage_temperature
     *
     * @param storageTemperature the value for tbl_commodity_information.storage_temperature
     *
     * @mbggenerated
     */
    public void setStorageTemperature(String storageTemperature) {
        this.storageTemperature = storageTemperature == null ? null : storageTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.removable
     *
     * @return the value of tbl_commodity_information.removable
     *
     * @mbggenerated
     */
    public Integer getRemovable() {
        return removable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.removable
     *
     * @param removable the value for tbl_commodity_information.removable
     *
     * @mbggenerated
     */
    public void setRemovable(Integer removable) {
        this.removable = removable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.encoder_number
     *
     * @return the value of tbl_commodity_information.encoder_number
     *
     * @mbggenerated
     */
    public Integer getEncoderNumber() {
        return encoderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.encoder_number
     *
     * @param encoderNumber the value for tbl_commodity_information.encoder_number
     *
     * @mbggenerated
     */
    public void setEncoderNumber(Integer encoderNumber) {
        this.encoderNumber = encoderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.encoder_height
     *
     * @return the value of tbl_commodity_information.encoder_height
     *
     * @mbggenerated
     */
    public Integer getEncoderHeight() {
        return encoderHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.encoder_height
     *
     * @param encoderHeight the value for tbl_commodity_information.encoder_height
     *
     * @mbggenerated
     */
    public void setEncoderHeight(Integer encoderHeight) {
        this.encoderHeight = encoderHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.production_date
     *
     * @return the value of tbl_commodity_information.production_date
     *
     * @mbggenerated
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.production_date
     *
     * @param productionDate the value for tbl_commodity_information.production_date
     *
     * @mbggenerated
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.qgp
     *
     * @return the value of tbl_commodity_information.qgp
     *
     * @mbggenerated
     */
    public Integer getQgp() {
        return qgp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.qgp
     *
     * @param qgp the value for tbl_commodity_information.qgp
     *
     * @mbggenerated
     */
    public void setQgp(Integer qgp) {
        this.qgp = qgp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commdity_images
     *
     * @return the value of tbl_commodity_information.commdity_images
     *
     * @mbggenerated
     */
    public String getCommdityImages() {
        return commdityImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commdity_images
     *
     * @param commdityImages the value for tbl_commodity_information.commdity_images
     *
     * @mbggenerated
     */
    public void setCommdityImages(String commdityImages) {
        this.commdityImages = commdityImages == null ? null : commdityImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.company
     *
     * @return the value of tbl_commodity_information.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.company
     *
     * @param company the value for tbl_commodity_information.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.disassemble_number
     *
     * @return the value of tbl_commodity_information.disassemble_number
     *
     * @mbggenerated
     */
    public Long getDisassembleNumber() {
        return disassembleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.disassemble_number
     *
     * @param disassembleNumber the value for tbl_commodity_information.disassemble_number
     *
     * @mbggenerated
     */
    public void setDisassembleNumber(Long disassembleNumber) {
        this.disassembleNumber = disassembleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.number_volume_ratio
     *
     * @return the value of tbl_commodity_information.number_volume_ratio
     *
     * @mbggenerated
     */
    public Double getNumberVolumeRatio() {
        return numberVolumeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.number_volume_ratio
     *
     * @param numberVolumeRatio the value for tbl_commodity_information.number_volume_ratio
     *
     * @mbggenerated
     */
    public void setNumberVolumeRatio(Double numberVolumeRatio) {
        this.numberVolumeRatio = numberVolumeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.number_gw_ratio
     *
     * @return the value of tbl_commodity_information.number_gw_ratio
     *
     * @mbggenerated
     */
    public Double getNumberGwRatio() {
        return numberGwRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.number_gw_ratio
     *
     * @param numberGwRatio the value for tbl_commodity_information.number_gw_ratio
     *
     * @mbggenerated
     */
    public void setNumberGwRatio(Double numberGwRatio) {
        this.numberGwRatio = numberGwRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.number_nw_ratio
     *
     * @return the value of tbl_commodity_information.number_nw_ratio
     *
     * @mbggenerated
     */
    public Double getNumberNwRatio() {
        return numberNwRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.number_nw_ratio
     *
     * @param numberNwRatio the value for tbl_commodity_information.number_nw_ratio
     *
     * @mbggenerated
     */
    public void setNumberNwRatio(Double numberNwRatio) {
        this.numberNwRatio = numberNwRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.dimension_unit
     *
     * @return the value of tbl_commodity_information.dimension_unit
     *
     * @mbggenerated
     */
    public String getDimensionUnit() {
        return dimensionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.dimension_unit
     *
     * @param dimensionUnit the value for tbl_commodity_information.dimension_unit
     *
     * @mbggenerated
     */
    public void setDimensionUnit(String dimensionUnit) {
        this.dimensionUnit = dimensionUnit == null ? null : dimensionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.item_length
     *
     * @return the value of tbl_commodity_information.item_length
     *
     * @mbggenerated
     */
    public Double getItemLength() {
        return itemLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.item_length
     *
     * @param itemLength the value for tbl_commodity_information.item_length
     *
     * @mbggenerated
     */
    public void setItemLength(Double itemLength) {
        this.itemLength = itemLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.item_wide
     *
     * @return the value of tbl_commodity_information.item_wide
     *
     * @mbggenerated
     */
    public Double getItemWide() {
        return itemWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.item_wide
     *
     * @param itemWide the value for tbl_commodity_information.item_wide
     *
     * @mbggenerated
     */
    public void setItemWide(Double itemWide) {
        this.itemWide = itemWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.item_high
     *
     * @return the value of tbl_commodity_information.item_high
     *
     * @mbggenerated
     */
    public Double getItemHigh() {
        return itemHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.item_high
     *
     * @param itemHigh the value for tbl_commodity_information.item_high
     *
     * @mbggenerated
     */
    public void setItemHigh(Double itemHigh) {
        this.itemHigh = itemHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.fcl_length
     *
     * @return the value of tbl_commodity_information.fcl_length
     *
     * @mbggenerated
     */
    public Double getFclLength() {
        return fclLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.fcl_length
     *
     * @param fclLength the value for tbl_commodity_information.fcl_length
     *
     * @mbggenerated
     */
    public void setFclLength(Double fclLength) {
        this.fclLength = fclLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.fcl_wide
     *
     * @return the value of tbl_commodity_information.fcl_wide
     *
     * @mbggenerated
     */
    public Double getFclWide() {
        return fclWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.fcl_wide
     *
     * @param fclWide the value for tbl_commodity_information.fcl_wide
     *
     * @mbggenerated
     */
    public void setFclWide(Double fclWide) {
        this.fclWide = fclWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.fcl_high
     *
     * @return the value of tbl_commodity_information.fcl_high
     *
     * @mbggenerated
     */
    public Double getFclHigh() {
        return fclHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.fcl_high
     *
     * @param fclHigh the value for tbl_commodity_information.fcl_high
     *
     * @mbggenerated
     */
    public void setFclHigh(Double fclHigh) {
        this.fclHigh = fclHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.single_volume
     *
     * @return the value of tbl_commodity_information.single_volume
     *
     * @mbggenerated
     */
    public Double getSingleVolume() {
        return singleVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.single_volume
     *
     * @param singleVolume the value for tbl_commodity_information.single_volume
     *
     * @mbggenerated
     */
    public void setSingleVolume(Double singleVolume) {
        this.singleVolume = singleVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.total_volume
     *
     * @return the value of tbl_commodity_information.total_volume
     *
     * @mbggenerated
     */
    public Double getTotalVolume() {
        return totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.total_volume
     *
     * @param totalVolume the value for tbl_commodity_information.total_volume
     *
     * @mbggenerated
     */
    public void setTotalVolume(Double totalVolume) {
        this.totalVolume = totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_remark
     *
     * @return the value of tbl_commodity_information.commodity_remark
     *
     * @mbggenerated
     */
    public String getCommodityRemark() {
        return commodityRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_remark
     *
     * @param commodityRemark the value for tbl_commodity_information.commodity_remark
     *
     * @mbggenerated
     */
    public void setCommodityRemark(String commodityRemark) {
        this.commodityRemark = commodityRemark == null ? null : commodityRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.status
     *
     * @return the value of tbl_commodity_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.status
     *
     * @param status the value for tbl_commodity_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.gross_weight
     *
     * @return the value of tbl_commodity_information.gross_weight
     *
     * @mbggenerated
     */
    public Long getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.gross_weight
     *
     * @param grossWeight the value for tbl_commodity_information.gross_weight
     *
     * @mbggenerated
     */
    public void setGrossWeight(Long grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.net_weight
     *
     * @return the value of tbl_commodity_information.net_weight
     *
     * @mbggenerated
     */
    public Long getNetWeight() {
        return netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.net_weight
     *
     * @param netWeight the value for tbl_commodity_information.net_weight
     *
     * @mbggenerated
     */
    public void setNetWeight(Long netWeight) {
        this.netWeight = netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_unit_price
     *
     * @return the value of tbl_commodity_information.commodity_unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getCommodityUnitPrice() {
        return commodityUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_unit_price
     *
     * @param commodityUnitPrice the value for tbl_commodity_information.commodity_unit_price
     *
     * @mbggenerated
     */
    public void setCommodityUnitPrice(BigDecimal commodityUnitPrice) {
        this.commodityUnitPrice = commodityUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.storage_unit
     *
     * @return the value of tbl_commodity_information.storage_unit
     *
     * @mbggenerated
     */
    public Integer getStorageUnit() {
        return storageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.storage_unit
     *
     * @param storageUnit the value for tbl_commodity_information.storage_unit
     *
     * @mbggenerated
     */
    public void setStorageUnit(Integer storageUnit) {
        this.storageUnit = storageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_total_price
     *
     * @return the value of tbl_commodity_information.commodity_total_price
     *
     * @mbggenerated
     */
    public BigDecimal getCommodityTotalPrice() {
        return commodityTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_total_price
     *
     * @param commodityTotalPrice the value for tbl_commodity_information.commodity_total_price
     *
     * @mbggenerated
     */
    public void setCommodityTotalPrice(BigDecimal commodityTotalPrice) {
        this.commodityTotalPrice = commodityTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_storage_type
     *
     * @return the value of tbl_commodity_information.commodity_storage_type
     *
     * @mbggenerated
     */
    public Integer getCommodityStorageType() {
        return commodityStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_storage_type
     *
     * @param commodityStorageType the value for tbl_commodity_information.commodity_storage_type
     *
     * @mbggenerated
     */
    public void setCommodityStorageType(Integer commodityStorageType) {
        this.commodityStorageType = commodityStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.mass_unit
     *
     * @return the value of tbl_commodity_information.mass_unit
     *
     * @mbggenerated
     */
    public String getMassUnit() {
        return massUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.mass_unit
     *
     * @param massUnit the value for tbl_commodity_information.mass_unit
     *
     * @mbggenerated
     */
    public void setMassUnit(String massUnit) {
        this.massUnit = massUnit == null ? null : massUnit.trim();
    }
}