package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CommodityClassInformation extends CommodityClassInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.parent_class_code
     *
     * @mbggenerated
     */
    private String parentClassCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.classification_name
     *
     * @mbggenerated
     */
    private String classificationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.parent_class_type
     *
     * @mbggenerated
     */
    private Integer parentClassType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.create_by
     *
     * @return the value of tbl_commodity_class_information.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.create_by
     *
     * @param createBy the value for tbl_commodity_class_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.create_date
     *
     * @return the value of tbl_commodity_class_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.create_date
     *
     * @param createDate the value for tbl_commodity_class_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.update_by
     *
     * @return the value of tbl_commodity_class_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.update_by
     *
     * @param updateBy the value for tbl_commodity_class_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.update_date
     *
     * @return the value of tbl_commodity_class_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.update_date
     *
     * @param updateDate the value for tbl_commodity_class_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.parent_class_code
     *
     * @return the value of tbl_commodity_class_information.parent_class_code
     *
     * @mbggenerated
     */
    public String getParentClassCode() {
        return parentClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.parent_class_code
     *
     * @param parentClassCode the value for tbl_commodity_class_information.parent_class_code
     *
     * @mbggenerated
     */
    public void setParentClassCode(String parentClassCode) {
        this.parentClassCode = parentClassCode == null ? null : parentClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.classification_name
     *
     * @return the value of tbl_commodity_class_information.classification_name
     *
     * @mbggenerated
     */
    public String getClassificationName() {
        return classificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.classification_name
     *
     * @param classificationName the value for tbl_commodity_class_information.classification_name
     *
     * @mbggenerated
     */
    public void setClassificationName(String classificationName) {
        this.classificationName = classificationName == null ? null : classificationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.parent_class_type
     *
     * @return the value of tbl_commodity_class_information.parent_class_type
     *
     * @mbggenerated
     */
    public Integer getParentClassType() {
        return parentClassType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.parent_class_type
     *
     * @param parentClassType the value for tbl_commodity_class_information.parent_class_type
     *
     * @mbggenerated
     */
    public void setParentClassType(Integer parentClassType) {
        this.parentClassType = parentClassType;
    }
}