package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class CommodityDetailedListBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_detaid_list_bean_id
     *
     * @mbggenerated
     */
    private String commodityDetaidListBeanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.detailed_list_id
     *
     * @mbggenerated
     */
    private String detailedListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.detailed_list_code
     *
     * @mbggenerated
     */
    private String detailedListCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_name
     *
     * @mbggenerated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_storage_type
     *
     * @mbggenerated
     */
    private Integer commodityStorageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.supplier_code
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.supplier_phone
     *
     * @mbggenerated
     */
    private String supplierPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_mn
     *
     * @mbggenerated
     */
    private String commodityMn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_detailed_list_bean.commodity_unit_price
     *
     * @mbggenerated
     */
    private BigDecimal commodityUnitPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.id
     *
     * @return the value of tbl_commodity_detailed_list_bean.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.id
     *
     * @param id the value for tbl_commodity_detailed_list_bean.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.create_date
     *
     * @return the value of tbl_commodity_detailed_list_bean.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.create_date
     *
     * @param createDate the value for tbl_commodity_detailed_list_bean.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.create_by
     *
     * @return the value of tbl_commodity_detailed_list_bean.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.create_by
     *
     * @param createBy the value for tbl_commodity_detailed_list_bean.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.update_by
     *
     * @return the value of tbl_commodity_detailed_list_bean.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.update_by
     *
     * @param updateBy the value for tbl_commodity_detailed_list_bean.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.update_date
     *
     * @return the value of tbl_commodity_detailed_list_bean.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.update_date
     *
     * @param updateDate the value for tbl_commodity_detailed_list_bean.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_detaid_list_bean_id
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_detaid_list_bean_id
     *
     * @mbggenerated
     */
    public String getCommodityDetaidListBeanId() {
        return commodityDetaidListBeanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_detaid_list_bean_id
     *
     * @param commodityDetaidListBeanId the value for tbl_commodity_detailed_list_bean.commodity_detaid_list_bean_id
     *
     * @mbggenerated
     */
    public void setCommodityDetaidListBeanId(String commodityDetaidListBeanId) {
        this.commodityDetaidListBeanId = commodityDetaidListBeanId == null ? null : commodityDetaidListBeanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.detailed_list_id
     *
     * @return the value of tbl_commodity_detailed_list_bean.detailed_list_id
     *
     * @mbggenerated
     */
    public String getDetailedListId() {
        return detailedListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.detailed_list_id
     *
     * @param detailedListId the value for tbl_commodity_detailed_list_bean.detailed_list_id
     *
     * @mbggenerated
     */
    public void setDetailedListId(String detailedListId) {
        this.detailedListId = detailedListId == null ? null : detailedListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.detailed_list_code
     *
     * @return the value of tbl_commodity_detailed_list_bean.detailed_list_code
     *
     * @mbggenerated
     */
    public String getDetailedListCode() {
        return detailedListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.detailed_list_code
     *
     * @param detailedListCode the value for tbl_commodity_detailed_list_bean.detailed_list_code
     *
     * @mbggenerated
     */
    public void setDetailedListCode(String detailedListCode) {
        this.detailedListCode = detailedListCode == null ? null : detailedListCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_id
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_id
     *
     * @param commodityId the value for tbl_commodity_detailed_list_bean.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_code
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_code
     *
     * @param commodityCode the value for tbl_commodity_detailed_list_bean.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_name
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_name
     *
     * @mbggenerated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_name
     *
     * @param commodityName the value for tbl_commodity_detailed_list_bean.commodity_name
     *
     * @mbggenerated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_storage_type
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_storage_type
     *
     * @mbggenerated
     */
    public Integer getCommodityStorageType() {
        return commodityStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_storage_type
     *
     * @param commodityStorageType the value for tbl_commodity_detailed_list_bean.commodity_storage_type
     *
     * @mbggenerated
     */
    public void setCommodityStorageType(Integer commodityStorageType) {
        this.commodityStorageType = commodityStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.count
     *
     * @return the value of tbl_commodity_detailed_list_bean.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.count
     *
     * @param count the value for tbl_commodity_detailed_list_bean.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.supplier_code
     *
     * @return the value of tbl_commodity_detailed_list_bean.supplier_code
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.supplier_code
     *
     * @param supplierCode the value for tbl_commodity_detailed_list_bean.supplier_code
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.supplier_name
     *
     * @return the value of tbl_commodity_detailed_list_bean.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.supplier_name
     *
     * @param supplierName the value for tbl_commodity_detailed_list_bean.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.supplier_phone
     *
     * @return the value of tbl_commodity_detailed_list_bean.supplier_phone
     *
     * @mbggenerated
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.supplier_phone
     *
     * @param supplierPhone the value for tbl_commodity_detailed_list_bean.supplier_phone
     *
     * @mbggenerated
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_mn
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_mn
     *
     * @mbggenerated
     */
    public String getCommodityMn() {
        return commodityMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_mn
     *
     * @param commodityMn the value for tbl_commodity_detailed_list_bean.commodity_mn
     *
     * @mbggenerated
     */
    public void setCommodityMn(String commodityMn) {
        this.commodityMn = commodityMn == null ? null : commodityMn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_detailed_list_bean.commodity_unit_price
     *
     * @return the value of tbl_commodity_detailed_list_bean.commodity_unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getCommodityUnitPrice() {
        return commodityUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_detailed_list_bean.commodity_unit_price
     *
     * @param commodityUnitPrice the value for tbl_commodity_detailed_list_bean.commodity_unit_price
     *
     * @mbggenerated
     */
    public void setCommodityUnitPrice(BigDecimal commodityUnitPrice) {
        this.commodityUnitPrice = commodityUnitPrice;
    }
}