package com.shiro.test.mvc.pojo;

public class CommodityInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_information.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.id
     *
     * @return the value of tbl_commodity_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.id
     *
     * @param id the value for tbl_commodity_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_information.commodity_id
     *
     * @return the value of tbl_commodity_information.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_information.commodity_id
     *
     * @param commodityId the value for tbl_commodity_information.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }
}