package com.shiro.test.mvc.pojo;

public class CommodityClassInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_commodity_class_information.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.id
     *
     * @return the value of tbl_commodity_class_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.id
     *
     * @param id the value for tbl_commodity_class_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_commodity_class_information.code
     *
     * @return the value of tbl_commodity_class_information.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_commodity_class_information.code
     *
     * @param code the value for tbl_commodity_class_information.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}