package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class DetailedListInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.applicant_id
     *
     * @mbggenerated
     */
    private String applicantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.applicant_code
     *
     * @mbggenerated
     */
    private String applicantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.applicant_name
     *
     * @mbggenerated
     */
    private String applicantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.detailed_list_id
     *
     * @mbggenerated
     */
    private String detailedListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.detailed_list_code
     *
     * @mbggenerated
     */
    private String detailedListCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.detailed_list_name
     *
     * @mbggenerated
     */
    private String detailedListName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.commodity_number
     *
     * @mbggenerated
     */
    private Integer commodityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.warehousing_out_of_stock_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date warehousingOutOfStockDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.staff_name
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.staff_code
     *
     * @mbggenerated
     */
    private String staffCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.detailed_list_type
     *
     * @mbggenerated
     */
    private Integer detailedListType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.receiving_deliverer_person_name
     *
     * @mbggenerated
     */
    private String receivingDelivererPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.receiving_deliverer_person_phone
     *
     * @mbggenerated
     */
    private String receivingDelivererPersonPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.receiving_deliverer_person_address
     *
     * @mbggenerated
     */
    private String receivingDelivererPersonAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.total_sum
     *
     * @mbggenerated
     */
    private BigDecimal totalSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.audit_by_id
     *
     * @mbggenerated
     */
    private String auditById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.audit_by_name
     *
     * @mbggenerated
     */
    private String auditByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.audit_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_detailed_list_information.out_storage_status
     *
     * @mbggenerated
     */
    private Integer outStorageStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.id
     *
     * @return the value of tbl_detailed_list_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.id
     *
     * @param id the value for tbl_detailed_list_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.create_by
     *
     * @return the value of tbl_detailed_list_information.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.create_by
     *
     * @param createBy the value for tbl_detailed_list_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.create_date
     *
     * @return the value of tbl_detailed_list_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.create_date
     *
     * @param createDate the value for tbl_detailed_list_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.update_by
     *
     * @return the value of tbl_detailed_list_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.update_by
     *
     * @param updateBy the value for tbl_detailed_list_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.applicant_id
     *
     * @return the value of tbl_detailed_list_information.applicant_id
     *
     * @mbggenerated
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.applicant_id
     *
     * @param applicantId the value for tbl_detailed_list_information.applicant_id
     *
     * @mbggenerated
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId == null ? null : applicantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.applicant_code
     *
     * @return the value of tbl_detailed_list_information.applicant_code
     *
     * @mbggenerated
     */
    public String getApplicantCode() {
        return applicantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.applicant_code
     *
     * @param applicantCode the value for tbl_detailed_list_information.applicant_code
     *
     * @mbggenerated
     */
    public void setApplicantCode(String applicantCode) {
        this.applicantCode = applicantCode == null ? null : applicantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.applicant_name
     *
     * @return the value of tbl_detailed_list_information.applicant_name
     *
     * @mbggenerated
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.applicant_name
     *
     * @param applicantName the value for tbl_detailed_list_information.applicant_name
     *
     * @mbggenerated
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName == null ? null : applicantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.update_date
     *
     * @return the value of tbl_detailed_list_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.update_date
     *
     * @param updateDate the value for tbl_detailed_list_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.detailed_list_id
     *
     * @return the value of tbl_detailed_list_information.detailed_list_id
     *
     * @mbggenerated
     */
    public String getDetailedListId() {
        return detailedListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.detailed_list_id
     *
     * @param detailedListId the value for tbl_detailed_list_information.detailed_list_id
     *
     * @mbggenerated
     */
    public void setDetailedListId(String detailedListId) {
        this.detailedListId = detailedListId == null ? null : detailedListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.detailed_list_code
     *
     * @return the value of tbl_detailed_list_information.detailed_list_code
     *
     * @mbggenerated
     */
    public String getDetailedListCode() {
        return detailedListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.detailed_list_code
     *
     * @param detailedListCode the value for tbl_detailed_list_information.detailed_list_code
     *
     * @mbggenerated
     */
    public void setDetailedListCode(String detailedListCode) {
        this.detailedListCode = detailedListCode == null ? null : detailedListCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.detailed_list_name
     *
     * @return the value of tbl_detailed_list_information.detailed_list_name
     *
     * @mbggenerated
     */
    public String getDetailedListName() {
        return detailedListName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.detailed_list_name
     *
     * @param detailedListName the value for tbl_detailed_list_information.detailed_list_name
     *
     * @mbggenerated
     */
    public void setDetailedListName(String detailedListName) {
        this.detailedListName = detailedListName == null ? null : detailedListName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.commodity_number
     *
     * @return the value of tbl_detailed_list_information.commodity_number
     *
     * @mbggenerated
     */
    public Integer getCommodityNumber() {
        return commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.commodity_number
     *
     * @param commodityNumber the value for tbl_detailed_list_information.commodity_number
     *
     * @mbggenerated
     */
    public void setCommodityNumber(Integer commodityNumber) {
        this.commodityNumber = commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.warehousing_out_of_stock_date
     *
     * @return the value of tbl_detailed_list_information.warehousing_out_of_stock_date
     *
     * @mbggenerated
     */
    public Date getWarehousingOutOfStockDate() {
        return warehousingOutOfStockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.warehousing_out_of_stock_date
     *
     * @param warehousingOutOfStockDate the value for tbl_detailed_list_information.warehousing_out_of_stock_date
     *
     * @mbggenerated
     */
    public void setWarehousingOutOfStockDate(Date warehousingOutOfStockDate) {
        this.warehousingOutOfStockDate = warehousingOutOfStockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.staff_name
     *
     * @return the value of tbl_detailed_list_information.staff_name
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.staff_name
     *
     * @param staffName the value for tbl_detailed_list_information.staff_name
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.staff_code
     *
     * @return the value of tbl_detailed_list_information.staff_code
     *
     * @mbggenerated
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.staff_code
     *
     * @param staffCode the value for tbl_detailed_list_information.staff_code
     *
     * @mbggenerated
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode == null ? null : staffCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.staff_id
     *
     * @return the value of tbl_detailed_list_information.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.staff_id
     *
     * @param staffId the value for tbl_detailed_list_information.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.detailed_list_type
     *
     * @return the value of tbl_detailed_list_information.detailed_list_type
     *
     * @mbggenerated
     */
    public Integer getDetailedListType() {
        return detailedListType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.detailed_list_type
     *
     * @param detailedListType the value for tbl_detailed_list_information.detailed_list_type
     *
     * @mbggenerated
     */
    public void setDetailedListType(Integer detailedListType) {
        this.detailedListType = detailedListType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.receiving_deliverer_person_name
     *
     * @return the value of tbl_detailed_list_information.receiving_deliverer_person_name
     *
     * @mbggenerated
     */
    public String getReceivingDelivererPersonName() {
        return receivingDelivererPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.receiving_deliverer_person_name
     *
     * @param receivingDelivererPersonName the value for tbl_detailed_list_information.receiving_deliverer_person_name
     *
     * @mbggenerated
     */
    public void setReceivingDelivererPersonName(String receivingDelivererPersonName) {
        this.receivingDelivererPersonName = receivingDelivererPersonName == null ? null : receivingDelivererPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.receiving_deliverer_person_phone
     *
     * @return the value of tbl_detailed_list_information.receiving_deliverer_person_phone
     *
     * @mbggenerated
     */
    public String getReceivingDelivererPersonPhone() {
        return receivingDelivererPersonPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.receiving_deliverer_person_phone
     *
     * @param receivingDelivererPersonPhone the value for tbl_detailed_list_information.receiving_deliverer_person_phone
     *
     * @mbggenerated
     */
    public void setReceivingDelivererPersonPhone(String receivingDelivererPersonPhone) {
        this.receivingDelivererPersonPhone = receivingDelivererPersonPhone == null ? null : receivingDelivererPersonPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.receiving_deliverer_person_address
     *
     * @return the value of tbl_detailed_list_information.receiving_deliverer_person_address
     *
     * @mbggenerated
     */
    public String getReceivingDelivererPersonAddress() {
        return receivingDelivererPersonAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.receiving_deliverer_person_address
     *
     * @param receivingDelivererPersonAddress the value for tbl_detailed_list_information.receiving_deliverer_person_address
     *
     * @mbggenerated
     */
    public void setReceivingDelivererPersonAddress(String receivingDelivererPersonAddress) {
        this.receivingDelivererPersonAddress = receivingDelivererPersonAddress == null ? null : receivingDelivererPersonAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.total_sum
     *
     * @return the value of tbl_detailed_list_information.total_sum
     *
     * @mbggenerated
     */
    public BigDecimal getTotalSum() {
        return totalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.total_sum
     *
     * @param totalSum the value for tbl_detailed_list_information.total_sum
     *
     * @mbggenerated
     */
    public void setTotalSum(BigDecimal totalSum) {
        this.totalSum = totalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.status
     *
     * @return the value of tbl_detailed_list_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.status
     *
     * @param status the value for tbl_detailed_list_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.audit_by_id
     *
     * @return the value of tbl_detailed_list_information.audit_by_id
     *
     * @mbggenerated
     */
    public String getAuditById() {
        return auditById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.audit_by_id
     *
     * @param auditById the value for tbl_detailed_list_information.audit_by_id
     *
     * @mbggenerated
     */
    public void setAuditById(String auditById) {
        this.auditById = auditById == null ? null : auditById.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.audit_by_name
     *
     * @return the value of tbl_detailed_list_information.audit_by_name
     *
     * @mbggenerated
     */
    public String getAuditByName() {
        return auditByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.audit_by_name
     *
     * @param auditByName the value for tbl_detailed_list_information.audit_by_name
     *
     * @mbggenerated
     */
    public void setAuditByName(String auditByName) {
        this.auditByName = auditByName == null ? null : auditByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.audit_date
     *
     * @return the value of tbl_detailed_list_information.audit_date
     *
     * @mbggenerated
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.audit_date
     *
     * @param auditDate the value for tbl_detailed_list_information.audit_date
     *
     * @mbggenerated
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_detailed_list_information.out_storage_status
     *
     * @return the value of tbl_detailed_list_information.out_storage_status
     *
     * @mbggenerated
     */
    public Integer getOutStorageStatus() {
        return outStorageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_detailed_list_information.out_storage_status
     *
     * @param outStorageStatus the value for tbl_detailed_list_information.out_storage_status
     *
     * @mbggenerated
     */
    public void setOutStorageStatus(Integer outStorageStatus) {
        this.outStorageStatus = outStorageStatus;
    }
}