package com.shiro.test.mvc.pojo;

import java.util.Date;

public class OutOfStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.out_of_stock_id
     *
     * @mbggenerated
     */
    private String outOfStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.out_of_stock_detailed_list_id
     *
     * @mbggenerated
     */
    private String outOfStockDetailedListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.out_of_stock_detailed_list_code
     *
     * @mbggenerated
     */
    private String outOfStockDetailedListCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.out_of_stock_no
     *
     * @mbggenerated
     */
    private String outOfStockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.warehouse_code
     *
     * @mbggenerated
     */
    private String warehouseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.warehouse_no
     *
     * @mbggenerated
     */
    private String warehouseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.warehouse_name
     *
     * @mbggenerated
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.shelf_position_id
     *
     * @mbggenerated
     */
    private String shelfPositionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.shelf_position_layer_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionLayerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.shelf_position_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.shelf_position_Row_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionRowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.shelf_position_code
     *
     * @mbggenerated
     */
    private String shelfPositionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_out_of_stock.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.id
     *
     * @return the value of tbl_out_of_stock.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.id
     *
     * @param id the value for tbl_out_of_stock.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.create_by
     *
     * @return the value of tbl_out_of_stock.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.create_by
     *
     * @param createBy the value for tbl_out_of_stock.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.create_date
     *
     * @return the value of tbl_out_of_stock.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.create_date
     *
     * @param createDate the value for tbl_out_of_stock.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.update_by
     *
     * @return the value of tbl_out_of_stock.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.update_by
     *
     * @param updateBy the value for tbl_out_of_stock.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.update_date
     *
     * @return the value of tbl_out_of_stock.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.update_date
     *
     * @param updateDate the value for tbl_out_of_stock.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.out_of_stock_id
     *
     * @return the value of tbl_out_of_stock.out_of_stock_id
     *
     * @mbggenerated
     */
    public String getOutOfStockId() {
        return outOfStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.out_of_stock_id
     *
     * @param outOfStockId the value for tbl_out_of_stock.out_of_stock_id
     *
     * @mbggenerated
     */
    public void setOutOfStockId(String outOfStockId) {
        this.outOfStockId = outOfStockId == null ? null : outOfStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.out_of_stock_detailed_list_id
     *
     * @return the value of tbl_out_of_stock.out_of_stock_detailed_list_id
     *
     * @mbggenerated
     */
    public String getOutOfStockDetailedListId() {
        return outOfStockDetailedListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.out_of_stock_detailed_list_id
     *
     * @param outOfStockDetailedListId the value for tbl_out_of_stock.out_of_stock_detailed_list_id
     *
     * @mbggenerated
     */
    public void setOutOfStockDetailedListId(String outOfStockDetailedListId) {
        this.outOfStockDetailedListId = outOfStockDetailedListId == null ? null : outOfStockDetailedListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.out_of_stock_detailed_list_code
     *
     * @return the value of tbl_out_of_stock.out_of_stock_detailed_list_code
     *
     * @mbggenerated
     */
    public String getOutOfStockDetailedListCode() {
        return outOfStockDetailedListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.out_of_stock_detailed_list_code
     *
     * @param outOfStockDetailedListCode the value for tbl_out_of_stock.out_of_stock_detailed_list_code
     *
     * @mbggenerated
     */
    public void setOutOfStockDetailedListCode(String outOfStockDetailedListCode) {
        this.outOfStockDetailedListCode = outOfStockDetailedListCode == null ? null : outOfStockDetailedListCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.out_of_stock_no
     *
     * @return the value of tbl_out_of_stock.out_of_stock_no
     *
     * @mbggenerated
     */
    public String getOutOfStockNo() {
        return outOfStockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.out_of_stock_no
     *
     * @param outOfStockNo the value for tbl_out_of_stock.out_of_stock_no
     *
     * @mbggenerated
     */
    public void setOutOfStockNo(String outOfStockNo) {
        this.outOfStockNo = outOfStockNo == null ? null : outOfStockNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.warehouse_code
     *
     * @return the value of tbl_out_of_stock.warehouse_code
     *
     * @mbggenerated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.warehouse_code
     *
     * @param warehouseCode the value for tbl_out_of_stock.warehouse_code
     *
     * @mbggenerated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.warehouse_id
     *
     * @return the value of tbl_out_of_stock.warehouse_id
     *
     * @mbggenerated
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.warehouse_id
     *
     * @param warehouseId the value for tbl_out_of_stock.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.warehouse_no
     *
     * @return the value of tbl_out_of_stock.warehouse_no
     *
     * @mbggenerated
     */
    public String getWarehouseNo() {
        return warehouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.warehouse_no
     *
     * @param warehouseNo the value for tbl_out_of_stock.warehouse_no
     *
     * @mbggenerated
     */
    public void setWarehouseNo(String warehouseNo) {
        this.warehouseNo = warehouseNo == null ? null : warehouseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.warehouse_name
     *
     * @return the value of tbl_out_of_stock.warehouse_name
     *
     * @mbggenerated
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.warehouse_name
     *
     * @param warehouseName the value for tbl_out_of_stock.warehouse_name
     *
     * @mbggenerated
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.commodity_code
     *
     * @return the value of tbl_out_of_stock.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.commodity_code
     *
     * @param commodityCode the value for tbl_out_of_stock.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.commodity_id
     *
     * @return the value of tbl_out_of_stock.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.commodity_id
     *
     * @param commodityId the value for tbl_out_of_stock.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.shelf_position_id
     *
     * @return the value of tbl_out_of_stock.shelf_position_id
     *
     * @mbggenerated
     */
    public String getShelfPositionId() {
        return shelfPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.shelf_position_id
     *
     * @param shelfPositionId the value for tbl_out_of_stock.shelf_position_id
     *
     * @mbggenerated
     */
    public void setShelfPositionId(String shelfPositionId) {
        this.shelfPositionId = shelfPositionId == null ? null : shelfPositionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.shelf_position_layer_no
     *
     * @return the value of tbl_out_of_stock.shelf_position_layer_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionLayerNo() {
        return shelfPositionLayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.shelf_position_layer_no
     *
     * @param shelfPositionLayerNo the value for tbl_out_of_stock.shelf_position_layer_no
     *
     * @mbggenerated
     */
    public void setShelfPositionLayerNo(Integer shelfPositionLayerNo) {
        this.shelfPositionLayerNo = shelfPositionLayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.shelf_position_no
     *
     * @return the value of tbl_out_of_stock.shelf_position_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionNo() {
        return shelfPositionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.shelf_position_no
     *
     * @param shelfPositionNo the value for tbl_out_of_stock.shelf_position_no
     *
     * @mbggenerated
     */
    public void setShelfPositionNo(Integer shelfPositionNo) {
        this.shelfPositionNo = shelfPositionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.shelf_position_Row_no
     *
     * @return the value of tbl_out_of_stock.shelf_position_Row_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionRowNo() {
        return shelfPositionRowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.shelf_position_Row_no
     *
     * @param shelfPositionRowNo the value for tbl_out_of_stock.shelf_position_Row_no
     *
     * @mbggenerated
     */
    public void setShelfPositionRowNo(Integer shelfPositionRowNo) {
        this.shelfPositionRowNo = shelfPositionRowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.shelf_position_code
     *
     * @return the value of tbl_out_of_stock.shelf_position_code
     *
     * @mbggenerated
     */
    public String getShelfPositionCode() {
        return shelfPositionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.shelf_position_code
     *
     * @param shelfPositionCode the value for tbl_out_of_stock.shelf_position_code
     *
     * @mbggenerated
     */
    public void setShelfPositionCode(String shelfPositionCode) {
        this.shelfPositionCode = shelfPositionCode == null ? null : shelfPositionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.remark
     *
     * @return the value of tbl_out_of_stock.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.remark
     *
     * @param remark the value for tbl_out_of_stock.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_out_of_stock.status
     *
     * @return the value of tbl_out_of_stock.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_out_of_stock.status
     *
     * @param status the value for tbl_out_of_stock.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}