package com.shiro.test.mvc.pojo;

import java.util.Date;

public class ShelfPositionInformation extends ShelfPositionInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.shelf_position_name
     *
     * @mbggenerated
     */
    private String shelfPositionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.shelf_position_layer_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionLayerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.shelf_position_Row_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionRowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.goods_shelves_id
     *
     * @mbggenerated
     */
    private String goodsShelvesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.goods_shelves_no
     *
     * @mbggenerated
     */
    private Integer goodsShelvesNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.goods_shelves_code
     *
     * @mbggenerated
     */
    private String goodsShelvesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.warehouse_code
     *
     * @mbggenerated
     */
    private String warehouseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.warehouse_name
     *
     * @mbggenerated
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.warehouse_type
     *
     * @mbggenerated
     */
    private Integer warehouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.warehouse_person_in_charge
     *
     * @mbggenerated
     */
    private String warehousePersonInCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.opening_date
     *
     * @mbggenerated
     */
    private Date openingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.dimension_unit
     *
     * @mbggenerated
     */
    private String dimensionUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.mass_unit
     *
     * @mbggenerated
     */
    private String massUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.area_unit
     *
     * @mbggenerated
     */
    private String areaUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.volume
     *
     * @mbggenerated
     */
    private Double volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.capacity
     *
     * @mbggenerated
     */
    private Double capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.area
     *
     * @mbggenerated
     */
    private Double area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.length
     *
     * @mbggenerated
     */
    private Double length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.wide
     *
     * @mbggenerated
     */
    private Double wide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.height
     *
     * @mbggenerated
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.usage_record
     *
     * @mbggenerated
     */
    private Integer usageRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.is_it_empty
     *
     * @mbggenerated
     */
    private Integer isItEmpty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.commodity_detaid_list_bean_warehousing_id
     *
     * @mbggenerated
     */
    private String commodityDetaidListBeanWarehousingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.detailed_list_warehousing_id
     *
     * @mbggenerated
     */
    private String detailedListWarehousingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.detailed_list_out_of_stock_id
     *
     * @mbggenerated
     */
    private String detailedListOutOfStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shelf_position_information.commodity_detaid_list_bean_out_of_stock_id
     *
     * @mbggenerated
     */
    private String commodityDetaidListBeanOutOfStockId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.create_by
     *
     * @return the value of tbl_shelf_position_information.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.create_by
     *
     * @param createBy the value for tbl_shelf_position_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.create_date
     *
     * @return the value of tbl_shelf_position_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.create_date
     *
     * @param createDate the value for tbl_shelf_position_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.update_by
     *
     * @return the value of tbl_shelf_position_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.update_by
     *
     * @param updateBy the value for tbl_shelf_position_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.update_date
     *
     * @return the value of tbl_shelf_position_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.update_date
     *
     * @param updateDate the value for tbl_shelf_position_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.shelf_position_name
     *
     * @return the value of tbl_shelf_position_information.shelf_position_name
     *
     * @mbggenerated
     */
    public String getShelfPositionName() {
        return shelfPositionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.shelf_position_name
     *
     * @param shelfPositionName the value for tbl_shelf_position_information.shelf_position_name
     *
     * @mbggenerated
     */
    public void setShelfPositionName(String shelfPositionName) {
        this.shelfPositionName = shelfPositionName == null ? null : shelfPositionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.shelf_position_layer_no
     *
     * @return the value of tbl_shelf_position_information.shelf_position_layer_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionLayerNo() {
        return shelfPositionLayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.shelf_position_layer_no
     *
     * @param shelfPositionLayerNo the value for tbl_shelf_position_information.shelf_position_layer_no
     *
     * @mbggenerated
     */
    public void setShelfPositionLayerNo(Integer shelfPositionLayerNo) {
        this.shelfPositionLayerNo = shelfPositionLayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.shelf_position_Row_no
     *
     * @return the value of tbl_shelf_position_information.shelf_position_Row_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionRowNo() {
        return shelfPositionRowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.shelf_position_Row_no
     *
     * @param shelfPositionRowNo the value for tbl_shelf_position_information.shelf_position_Row_no
     *
     * @mbggenerated
     */
    public void setShelfPositionRowNo(Integer shelfPositionRowNo) {
        this.shelfPositionRowNo = shelfPositionRowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.goods_shelves_id
     *
     * @return the value of tbl_shelf_position_information.goods_shelves_id
     *
     * @mbggenerated
     */
    public String getGoodsShelvesId() {
        return goodsShelvesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.goods_shelves_id
     *
     * @param goodsShelvesId the value for tbl_shelf_position_information.goods_shelves_id
     *
     * @mbggenerated
     */
    public void setGoodsShelvesId(String goodsShelvesId) {
        this.goodsShelvesId = goodsShelvesId == null ? null : goodsShelvesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.goods_shelves_no
     *
     * @return the value of tbl_shelf_position_information.goods_shelves_no
     *
     * @mbggenerated
     */
    public Integer getGoodsShelvesNo() {
        return goodsShelvesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.goods_shelves_no
     *
     * @param goodsShelvesNo the value for tbl_shelf_position_information.goods_shelves_no
     *
     * @mbggenerated
     */
    public void setGoodsShelvesNo(Integer goodsShelvesNo) {
        this.goodsShelvesNo = goodsShelvesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.goods_shelves_code
     *
     * @return the value of tbl_shelf_position_information.goods_shelves_code
     *
     * @mbggenerated
     */
    public String getGoodsShelvesCode() {
        return goodsShelvesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.goods_shelves_code
     *
     * @param goodsShelvesCode the value for tbl_shelf_position_information.goods_shelves_code
     *
     * @mbggenerated
     */
    public void setGoodsShelvesCode(String goodsShelvesCode) {
        this.goodsShelvesCode = goodsShelvesCode == null ? null : goodsShelvesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.warehouse_id
     *
     * @return the value of tbl_shelf_position_information.warehouse_id
     *
     * @mbggenerated
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.warehouse_id
     *
     * @param warehouseId the value for tbl_shelf_position_information.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.warehouse_code
     *
     * @return the value of tbl_shelf_position_information.warehouse_code
     *
     * @mbggenerated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.warehouse_code
     *
     * @param warehouseCode the value for tbl_shelf_position_information.warehouse_code
     *
     * @mbggenerated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.warehouse_name
     *
     * @return the value of tbl_shelf_position_information.warehouse_name
     *
     * @mbggenerated
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.warehouse_name
     *
     * @param warehouseName the value for tbl_shelf_position_information.warehouse_name
     *
     * @mbggenerated
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.warehouse_type
     *
     * @return the value of tbl_shelf_position_information.warehouse_type
     *
     * @mbggenerated
     */
    public Integer getWarehouseType() {
        return warehouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.warehouse_type
     *
     * @param warehouseType the value for tbl_shelf_position_information.warehouse_type
     *
     * @mbggenerated
     */
    public void setWarehouseType(Integer warehouseType) {
        this.warehouseType = warehouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.warehouse_person_in_charge
     *
     * @return the value of tbl_shelf_position_information.warehouse_person_in_charge
     *
     * @mbggenerated
     */
    public String getWarehousePersonInCharge() {
        return warehousePersonInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.warehouse_person_in_charge
     *
     * @param warehousePersonInCharge the value for tbl_shelf_position_information.warehouse_person_in_charge
     *
     * @mbggenerated
     */
    public void setWarehousePersonInCharge(String warehousePersonInCharge) {
        this.warehousePersonInCharge = warehousePersonInCharge == null ? null : warehousePersonInCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.opening_date
     *
     * @return the value of tbl_shelf_position_information.opening_date
     *
     * @mbggenerated
     */
    public Date getOpeningDate() {
        return openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.opening_date
     *
     * @param openingDate the value for tbl_shelf_position_information.opening_date
     *
     * @mbggenerated
     */
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.dimension_unit
     *
     * @return the value of tbl_shelf_position_information.dimension_unit
     *
     * @mbggenerated
     */
    public String getDimensionUnit() {
        return dimensionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.dimension_unit
     *
     * @param dimensionUnit the value for tbl_shelf_position_information.dimension_unit
     *
     * @mbggenerated
     */
    public void setDimensionUnit(String dimensionUnit) {
        this.dimensionUnit = dimensionUnit == null ? null : dimensionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.mass_unit
     *
     * @return the value of tbl_shelf_position_information.mass_unit
     *
     * @mbggenerated
     */
    public String getMassUnit() {
        return massUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.mass_unit
     *
     * @param massUnit the value for tbl_shelf_position_information.mass_unit
     *
     * @mbggenerated
     */
    public void setMassUnit(String massUnit) {
        this.massUnit = massUnit == null ? null : massUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.area_unit
     *
     * @return the value of tbl_shelf_position_information.area_unit
     *
     * @mbggenerated
     */
    public String getAreaUnit() {
        return areaUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.area_unit
     *
     * @param areaUnit the value for tbl_shelf_position_information.area_unit
     *
     * @mbggenerated
     */
    public void setAreaUnit(String areaUnit) {
        this.areaUnit = areaUnit == null ? null : areaUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.volume
     *
     * @return the value of tbl_shelf_position_information.volume
     *
     * @mbggenerated
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.volume
     *
     * @param volume the value for tbl_shelf_position_information.volume
     *
     * @mbggenerated
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.capacity
     *
     * @return the value of tbl_shelf_position_information.capacity
     *
     * @mbggenerated
     */
    public Double getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.capacity
     *
     * @param capacity the value for tbl_shelf_position_information.capacity
     *
     * @mbggenerated
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.area
     *
     * @return the value of tbl_shelf_position_information.area
     *
     * @mbggenerated
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.area
     *
     * @param area the value for tbl_shelf_position_information.area
     *
     * @mbggenerated
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.length
     *
     * @return the value of tbl_shelf_position_information.length
     *
     * @mbggenerated
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.length
     *
     * @param length the value for tbl_shelf_position_information.length
     *
     * @mbggenerated
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.wide
     *
     * @return the value of tbl_shelf_position_information.wide
     *
     * @mbggenerated
     */
    public Double getWide() {
        return wide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.wide
     *
     * @param wide the value for tbl_shelf_position_information.wide
     *
     * @mbggenerated
     */
    public void setWide(Double wide) {
        this.wide = wide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.height
     *
     * @return the value of tbl_shelf_position_information.height
     *
     * @mbggenerated
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.height
     *
     * @param height the value for tbl_shelf_position_information.height
     *
     * @mbggenerated
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.status
     *
     * @return the value of tbl_shelf_position_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.status
     *
     * @param status the value for tbl_shelf_position_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.usage_record
     *
     * @return the value of tbl_shelf_position_information.usage_record
     *
     * @mbggenerated
     */
    public Integer getUsageRecord() {
        return usageRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.usage_record
     *
     * @param usageRecord the value for tbl_shelf_position_information.usage_record
     *
     * @mbggenerated
     */
    public void setUsageRecord(Integer usageRecord) {
        this.usageRecord = usageRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.is_it_empty
     *
     * @return the value of tbl_shelf_position_information.is_it_empty
     *
     * @mbggenerated
     */
    public Integer getIsItEmpty() {
        return isItEmpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.is_it_empty
     *
     * @param isItEmpty the value for tbl_shelf_position_information.is_it_empty
     *
     * @mbggenerated
     */
    public void setIsItEmpty(Integer isItEmpty) {
        this.isItEmpty = isItEmpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.commodity_id
     *
     * @return the value of tbl_shelf_position_information.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.commodity_id
     *
     * @param commodityId the value for tbl_shelf_position_information.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.commodity_detaid_list_bean_warehousing_id
     *
     * @return the value of tbl_shelf_position_information.commodity_detaid_list_bean_warehousing_id
     *
     * @mbggenerated
     */
    public String getCommodityDetaidListBeanWarehousingId() {
        return commodityDetaidListBeanWarehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.commodity_detaid_list_bean_warehousing_id
     *
     * @param commodityDetaidListBeanWarehousingId the value for tbl_shelf_position_information.commodity_detaid_list_bean_warehousing_id
     *
     * @mbggenerated
     */
    public void setCommodityDetaidListBeanWarehousingId(String commodityDetaidListBeanWarehousingId) {
        this.commodityDetaidListBeanWarehousingId = commodityDetaidListBeanWarehousingId == null ? null : commodityDetaidListBeanWarehousingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.detailed_list_warehousing_id
     *
     * @return the value of tbl_shelf_position_information.detailed_list_warehousing_id
     *
     * @mbggenerated
     */
    public String getDetailedListWarehousingId() {
        return detailedListWarehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.detailed_list_warehousing_id
     *
     * @param detailedListWarehousingId the value for tbl_shelf_position_information.detailed_list_warehousing_id
     *
     * @mbggenerated
     */
    public void setDetailedListWarehousingId(String detailedListWarehousingId) {
        this.detailedListWarehousingId = detailedListWarehousingId == null ? null : detailedListWarehousingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.detailed_list_out_of_stock_id
     *
     * @return the value of tbl_shelf_position_information.detailed_list_out_of_stock_id
     *
     * @mbggenerated
     */
    public String getDetailedListOutOfStockId() {
        return detailedListOutOfStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.detailed_list_out_of_stock_id
     *
     * @param detailedListOutOfStockId the value for tbl_shelf_position_information.detailed_list_out_of_stock_id
     *
     * @mbggenerated
     */
    public void setDetailedListOutOfStockId(String detailedListOutOfStockId) {
        this.detailedListOutOfStockId = detailedListOutOfStockId == null ? null : detailedListOutOfStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shelf_position_information.commodity_detaid_list_bean_out_of_stock_id
     *
     * @return the value of tbl_shelf_position_information.commodity_detaid_list_bean_out_of_stock_id
     *
     * @mbggenerated
     */
    public String getCommodityDetaidListBeanOutOfStockId() {
        return commodityDetaidListBeanOutOfStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shelf_position_information.commodity_detaid_list_bean_out_of_stock_id
     *
     * @param commodityDetaidListBeanOutOfStockId the value for tbl_shelf_position_information.commodity_detaid_list_bean_out_of_stock_id
     *
     * @mbggenerated
     */
    public void setCommodityDetaidListBeanOutOfStockId(String commodityDetaidListBeanOutOfStockId) {
        this.commodityDetaidListBeanOutOfStockId = commodityDetaidListBeanOutOfStockId == null ? null : commodityDetaidListBeanOutOfStockId.trim();
    }
}