package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class SuppliersInformation extends SuppliersInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.id
     *
     * @mbggenerated
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.subordinate_departments
     *
     * @mbggenerated
     */
    private String subordinateDepartments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.kaleidoscope
     *
     * @mbggenerated
     */
    private String kaleidoscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.chinese_full_name
     *
     * @mbggenerated
     */
    private String chineseFullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.mnemonic_code
     *
     * @mbggenerated
     */
    private String mnemonicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_abbreviation
     *
     * @mbggenerated
     */
    private String supplierAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_code
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_name_english
     *
     * @mbggenerated
     */
    private String supplierNameEnglish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_status
     *
     * @mbggenerated
     */
    private Integer supplierStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.enterprise_attribute
     *
     * @mbggenerated
     */
    private Integer enterpriseAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_level
     *
     * @mbggenerated
     */
    private Integer supplierLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.industry_involved
     *
     * @mbggenerated
     */
    private Integer industryInvolved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.application_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date applicationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_property
     *
     * @mbggenerated
     */
    private BigDecimal supplierProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.organization_code
     *
     * @mbggenerated
     */
    private String organizationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.postal_code
     *
     * @mbggenerated
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.main_contact
     *
     * @mbggenerated
     */
    private String mainContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_phone
     *
     * @mbggenerated
     */
    private String supplierPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.home_page
     *
     * @mbggenerated
     */
    private String homePage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.legal_person
     *
     * @mbggenerated
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.corporate_id_number
     *
     * @mbggenerated
     */
    private String corporateIdNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.registered_capital
     *
     * @mbggenerated
     */
    private BigDecimal registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.business_license_no
     *
     * @mbggenerated
     */
    private String businessLicenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.tax_registration_no
     *
     * @mbggenerated
     */
    private String taxRegistrationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.road_transport_permit
     *
     * @mbggenerated
     */
    private String roadTransportPermit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.main_business
     *
     * @mbggenerated
     */
    private String mainBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.cooperation_intention
     *
     * @mbggenerated
     */
    private String cooperationIntention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.approval_authority
     *
     * @mbggenerated
     */
    private String approvalAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.approval_no
     *
     * @mbggenerated
     */
    private String approvalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.registration_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date registrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.contacts_two
     *
     * @mbggenerated
     */
    private String contactsTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.phone_two
     *
     * @mbggenerated
     */
    private String phoneTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.create_by
     *
     * @return the value of tbl_supplier_information.create_by
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_id
     *
     * @return the value of tbl_supplier_information.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_id
     *
     * @param supplierId the value for tbl_supplier_information.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.id
     *
     * @return the value of tbl_supplier_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.id
     *
     * @param id the value for tbl_supplier_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }


    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.create_by
     *
     * @param createBy the value for tbl_supplier_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.create_date
     *
     * @return the value of tbl_supplier_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.create_date
     *
     * @param createDate the value for tbl_supplier_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.update_by
     *
     * @return the value of tbl_supplier_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.update_by
     *
     * @param updateBy the value for tbl_supplier_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.update_date
     *
     * @return the value of tbl_supplier_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.update_date
     *
     * @param updateDate the value for tbl_supplier_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.subordinate_departments
     *
     * @return the value of tbl_supplier_information.subordinate_departments
     *
     * @mbggenerated
     */
    public String getSubordinateDepartments() {
        return subordinateDepartments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.subordinate_departments
     *
     * @param subordinateDepartments the value for tbl_supplier_information.subordinate_departments
     *
     * @mbggenerated
     */
    public void setSubordinateDepartments(String subordinateDepartments) {
        this.subordinateDepartments = subordinateDepartments == null ? null : subordinateDepartments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.kaleidoscope
     *
     * @return the value of tbl_supplier_information.kaleidoscope
     *
     * @mbggenerated
     */
    public String getKaleidoscope() {
        return kaleidoscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.kaleidoscope
     *
     * @param kaleidoscope the value for tbl_supplier_information.kaleidoscope
     *
     * @mbggenerated
     */
    public void setKaleidoscope(String kaleidoscope) {
        this.kaleidoscope = kaleidoscope == null ? null : kaleidoscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.chinese_full_name
     *
     * @return the value of tbl_supplier_information.chinese_full_name
     *
     * @mbggenerated
     */
    public String getChineseFullName() {
        return chineseFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.chinese_full_name
     *
     * @param chineseFullName the value for tbl_supplier_information.chinese_full_name
     *
     * @mbggenerated
     */
    public void setChineseFullName(String chineseFullName) {
        this.chineseFullName = chineseFullName == null ? null : chineseFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.mnemonic_code
     *
     * @return the value of tbl_supplier_information.mnemonic_code
     *
     * @mbggenerated
     */
    public String getMnemonicCode() {
        return mnemonicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.mnemonic_code
     *
     * @param mnemonicCode the value for tbl_supplier_information.mnemonic_code
     *
     * @mbggenerated
     */
    public void setMnemonicCode(String mnemonicCode) {
        this.mnemonicCode = mnemonicCode == null ? null : mnemonicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_abbreviation
     *
     * @return the value of tbl_supplier_information.supplier_abbreviation
     *
     * @mbggenerated
     */
    public String getSupplierAbbreviation() {
        return supplierAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_abbreviation
     *
     * @param supplierAbbreviation the value for tbl_supplier_information.supplier_abbreviation
     *
     * @mbggenerated
     */
    public void setSupplierAbbreviation(String supplierAbbreviation) {
        this.supplierAbbreviation = supplierAbbreviation == null ? null : supplierAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_code
     *
     * @return the value of tbl_supplier_information.supplier_code
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_code
     *
     * @param supplierCode the value for tbl_supplier_information.supplier_code
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_name_english
     *
     * @return the value of tbl_supplier_information.supplier_name_english
     *
     * @mbggenerated
     */
    public String getSupplierNameEnglish() {
        return supplierNameEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_name_english
     *
     * @param supplierNameEnglish the value for tbl_supplier_information.supplier_name_english
     *
     * @mbggenerated
     */
    public void setSupplierNameEnglish(String supplierNameEnglish) {
        this.supplierNameEnglish = supplierNameEnglish == null ? null : supplierNameEnglish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_status
     *
     * @return the value of tbl_supplier_information.supplier_status
     *
     * @mbggenerated
     */
    public Integer getSupplierStatus() {
        return supplierStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_status
     *
     * @param supplierStatus the value for tbl_supplier_information.supplier_status
     *
     * @mbggenerated
     */
    public void setSupplierStatus(Integer supplierStatus) {
        this.supplierStatus = supplierStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.enterprise_attribute
     *
     * @return the value of tbl_supplier_information.enterprise_attribute
     *
     * @mbggenerated
     */
    public Integer getEnterpriseAttribute() {
        return enterpriseAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.enterprise_attribute
     *
     * @param enterpriseAttribute the value for tbl_supplier_information.enterprise_attribute
     *
     * @mbggenerated
     */
    public void setEnterpriseAttribute(Integer enterpriseAttribute) {
        this.enterpriseAttribute = enterpriseAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_level
     *
     * @return the value of tbl_supplier_information.supplier_level
     *
     * @mbggenerated
     */
    public Integer getSupplierLevel() {
        return supplierLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_level
     *
     * @param supplierLevel the value for tbl_supplier_information.supplier_level
     *
     * @mbggenerated
     */
    public void setSupplierLevel(Integer supplierLevel) {
        this.supplierLevel = supplierLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.industry_involved
     *
     * @return the value of tbl_supplier_information.industry_involved
     *
     * @mbggenerated
     */
    public Integer getIndustryInvolved() {
        return industryInvolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.industry_involved
     *
     * @param industryInvolved the value for tbl_supplier_information.industry_involved
     *
     * @mbggenerated
     */
    public void setIndustryInvolved(Integer industryInvolved) {
        this.industryInvolved = industryInvolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.application_date
     *
     * @return the value of tbl_supplier_information.application_date
     *
     * @mbggenerated
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.application_date
     *
     * @param applicationDate the value for tbl_supplier_information.application_date
     *
     * @mbggenerated
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_property
     *
     * @return the value of tbl_supplier_information.supplier_property
     *
     * @mbggenerated
     */
    public BigDecimal getSupplierProperty() {
        return supplierProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_property
     *
     * @param supplierProperty the value for tbl_supplier_information.supplier_property
     *
     * @mbggenerated
     */
    public void setSupplierProperty(BigDecimal supplierProperty) {
        this.supplierProperty = supplierProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.organization_code
     *
     * @return the value of tbl_supplier_information.organization_code
     *
     * @mbggenerated
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.organization_code
     *
     * @param organizationCode the value for tbl_supplier_information.organization_code
     *
     * @mbggenerated
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.province_code
     *
     * @return the value of tbl_supplier_information.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.province_code
     *
     * @param provinceCode the value for tbl_supplier_information.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.city_code
     *
     * @return the value of tbl_supplier_information.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.city_code
     *
     * @param cityCode the value for tbl_supplier_information.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.county_code
     *
     * @return the value of tbl_supplier_information.county_code
     *
     * @mbggenerated
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.county_code
     *
     * @param countyCode the value for tbl_supplier_information.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.address
     *
     * @return the value of tbl_supplier_information.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.address
     *
     * @param address the value for tbl_supplier_information.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.postal_code
     *
     * @return the value of tbl_supplier_information.postal_code
     *
     * @mbggenerated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.postal_code
     *
     * @param postalCode the value for tbl_supplier_information.postal_code
     *
     * @mbggenerated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.main_contact
     *
     * @return the value of tbl_supplier_information.main_contact
     *
     * @mbggenerated
     */
    public String getMainContact() {
        return mainContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.main_contact
     *
     * @param mainContact the value for tbl_supplier_information.main_contact
     *
     * @mbggenerated
     */
    public void setMainContact(String mainContact) {
        this.mainContact = mainContact == null ? null : mainContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_phone
     *
     * @return the value of tbl_supplier_information.supplier_phone
     *
     * @mbggenerated
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_phone
     *
     * @param supplierPhone the value for tbl_supplier_information.supplier_phone
     *
     * @mbggenerated
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.email
     *
     * @return the value of tbl_supplier_information.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.email
     *
     * @param email the value for tbl_supplier_information.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.home_page
     *
     * @return the value of tbl_supplier_information.home_page
     *
     * @mbggenerated
     */
    public String getHomePage() {
        return homePage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.home_page
     *
     * @param homePage the value for tbl_supplier_information.home_page
     *
     * @mbggenerated
     */
    public void setHomePage(String homePage) {
        this.homePage = homePage == null ? null : homePage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.legal_person
     *
     * @return the value of tbl_supplier_information.legal_person
     *
     * @mbggenerated
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.legal_person
     *
     * @param legalPerson the value for tbl_supplier_information.legal_person
     *
     * @mbggenerated
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.corporate_id_number
     *
     * @return the value of tbl_supplier_information.corporate_id_number
     *
     * @mbggenerated
     */
    public String getCorporateIdNumber() {
        return corporateIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.corporate_id_number
     *
     * @param corporateIdNumber the value for tbl_supplier_information.corporate_id_number
     *
     * @mbggenerated
     */
    public void setCorporateIdNumber(String corporateIdNumber) {
        this.corporateIdNumber = corporateIdNumber == null ? null : corporateIdNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.registered_capital
     *
     * @return the value of tbl_supplier_information.registered_capital
     *
     * @mbggenerated
     */
    public BigDecimal getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.registered_capital
     *
     * @param registeredCapital the value for tbl_supplier_information.registered_capital
     *
     * @mbggenerated
     */
    public void setRegisteredCapital(BigDecimal registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.currency
     *
     * @return the value of tbl_supplier_information.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.currency
     *
     * @param currency the value for tbl_supplier_information.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.business_license_no
     *
     * @return the value of tbl_supplier_information.business_license_no
     *
     * @mbggenerated
     */
    public String getBusinessLicenseNo() {
        return businessLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.business_license_no
     *
     * @param businessLicenseNo the value for tbl_supplier_information.business_license_no
     *
     * @mbggenerated
     */
    public void setBusinessLicenseNo(String businessLicenseNo) {
        this.businessLicenseNo = businessLicenseNo == null ? null : businessLicenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.tax_registration_no
     *
     * @return the value of tbl_supplier_information.tax_registration_no
     *
     * @mbggenerated
     */
    public String getTaxRegistrationNo() {
        return taxRegistrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.tax_registration_no
     *
     * @param taxRegistrationNo the value for tbl_supplier_information.tax_registration_no
     *
     * @mbggenerated
     */
    public void setTaxRegistrationNo(String taxRegistrationNo) {
        this.taxRegistrationNo = taxRegistrationNo == null ? null : taxRegistrationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.road_transport_permit
     *
     * @return the value of tbl_supplier_information.road_transport_permit
     *
     * @mbggenerated
     */
    public String getRoadTransportPermit() {
        return roadTransportPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.road_transport_permit
     *
     * @param roadTransportPermit the value for tbl_supplier_information.road_transport_permit
     *
     * @mbggenerated
     */
    public void setRoadTransportPermit(String roadTransportPermit) {
        this.roadTransportPermit = roadTransportPermit == null ? null : roadTransportPermit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.main_business
     *
     * @return the value of tbl_supplier_information.main_business
     *
     * @mbggenerated
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.main_business
     *
     * @param mainBusiness the value for tbl_supplier_information.main_business
     *
     * @mbggenerated
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness == null ? null : mainBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.cooperation_intention
     *
     * @return the value of tbl_supplier_information.cooperation_intention
     *
     * @mbggenerated
     */
    public String getCooperationIntention() {
        return cooperationIntention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.cooperation_intention
     *
     * @param cooperationIntention the value for tbl_supplier_information.cooperation_intention
     *
     * @mbggenerated
     */
    public void setCooperationIntention(String cooperationIntention) {
        this.cooperationIntention = cooperationIntention == null ? null : cooperationIntention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.approval_authority
     *
     * @return the value of tbl_supplier_information.approval_authority
     *
     * @mbggenerated
     */
    public String getApprovalAuthority() {
        return approvalAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.approval_authority
     *
     * @param approvalAuthority the value for tbl_supplier_information.approval_authority
     *
     * @mbggenerated
     */
    public void setApprovalAuthority(String approvalAuthority) {
        this.approvalAuthority = approvalAuthority == null ? null : approvalAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.approval_no
     *
     * @return the value of tbl_supplier_information.approval_no
     *
     * @mbggenerated
     */
    public String getApprovalNo() {
        return approvalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.approval_no
     *
     * @param approvalNo the value for tbl_supplier_information.approval_no
     *
     * @mbggenerated
     */
    public void setApprovalNo(String approvalNo) {
        this.approvalNo = approvalNo == null ? null : approvalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.registration_date
     *
     * @return the value of tbl_supplier_information.registration_date
     *
     * @mbggenerated
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.registration_date
     *
     * @param registrationDate the value for tbl_supplier_information.registration_date
     *
     * @mbggenerated
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.remark
     *
     * @return the value of tbl_supplier_information.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.remark
     *
     * @param remark the value for tbl_supplier_information.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.contacts_two
     *
     * @return the value of tbl_supplier_information.contacts_two
     *
     * @mbggenerated
     */
    public String getContactsTwo() {
        return contactsTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.contacts_two
     *
     * @param contactsTwo the value for tbl_supplier_information.contacts_two
     *
     * @mbggenerated
     */
    public void setContactsTwo(String contactsTwo) {
        this.contactsTwo = contactsTwo == null ? null : contactsTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.phone_two
     *
     * @return the value of tbl_supplier_information.phone_two
     *
     * @mbggenerated
     */
    public String getPhoneTwo() {
        return phoneTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.phone_two
     *
     * @param phoneTwo the value for tbl_supplier_information.phone_two
     *
     * @mbggenerated
     */
    public void setPhoneTwo(String phoneTwo) {
        this.phoneTwo = phoneTwo == null ? null : phoneTwo.trim();
    }

    @Override
    public String toString() {
        return "SuppliersInformation{" +
                "supplierId='" + supplierId + '\'' +
                ", id='" + id + '\'' +
                ", createBy='" + createBy + '\'' +
                ", createDate=" + createDate +
                ", updateBy='" + updateBy + '\'' +
                ", updateDate=" + updateDate +
                ", subordinateDepartments='" + subordinateDepartments + '\'' +
                ", kaleidoscope='" + kaleidoscope + '\'' +
                ", chineseFullName='" + chineseFullName + '\'' +
                ", mnemonicCode='" + mnemonicCode + '\'' +
                ", supplierAbbreviation='" + supplierAbbreviation + '\'' +
                ", supplierCode='" + supplierCode + '\'' +
                ", supplierNameEnglish='" + supplierNameEnglish + '\'' +
                ", supplierStatus=" + supplierStatus +
                ", enterpriseAttribute=" + enterpriseAttribute +
                ", supplierLevel=" + supplierLevel +
                ", industryInvolved=" + industryInvolved +
                ", applicationDate=" + applicationDate +
                ", supplierProperty=" + supplierProperty +
                ", organizationCode='" + organizationCode + '\'' +
                ", provinceCode='" + provinceCode + '\'' +
                ", cityCode='" + cityCode + '\'' +
                ", countyCode='" + countyCode + '\'' +
                ", address='" + address + '\'' +
                ", postalCode='" + postalCode + '\'' +
                ", mainContact='" + mainContact + '\'' +
                ", supplierPhone='" + supplierPhone + '\'' +
                ", email='" + email + '\'' +
                ", homePage='" + homePage + '\'' +
                ", legalPerson='" + legalPerson + '\'' +
                ", corporateIdNumber='" + corporateIdNumber + '\'' +
                ", registeredCapital=" + registeredCapital +
                ", currency='" + currency + '\'' +
                ", businessLicenseNo='" + businessLicenseNo + '\'' +
                ", taxRegistrationNo='" + taxRegistrationNo + '\'' +
                ", roadTransportPermit='" + roadTransportPermit + '\'' +
                ", mainBusiness='" + mainBusiness + '\'' +
                ", cooperationIntention='" + cooperationIntention + '\'' +
                ", approvalAuthority='" + approvalAuthority + '\'' +
                ", approvalNo='" + approvalNo + '\'' +
                ", registrationDate=" + registrationDate +
                ", remark='" + remark + '\'' +
                ", contactsTwo='" + contactsTwo + '\'' +
                ", phoneTwo='" + phoneTwo + '\'' +
                '}';
    }
}