package com.shiro.test.mvc.pojo;

public class SuppliersInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.supplier_id
     *
     * @return the value of tbl_supplier_information.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.supplier_id
     *
     * @param supplierId the value for tbl_supplier_information.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_information.id
     *
     * @return the value of tbl_supplier_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_information.id
     *
     * @param id the value for tbl_supplier_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Override
    public String toString() {
        return "SuppliersInformationKey{" +
                "supplierId='" + supplierId + '\'' +
                ", id='" + id + '\'' +
                '}';
    }
}