package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class UserRoleInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shiro_user_role_informtion.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.user_id
     *
     * @return the value of tbl_shiro_user_role_informtion.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.user_id
     *
     * @param userId the value for tbl_shiro_user_role_informtion.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.role_id
     *
     * @return the value of tbl_shiro_user_role_informtion.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.role_id
     *
     * @param roleId the value for tbl_shiro_user_role_informtion.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.create_by
     *
     * @return the value of tbl_shiro_user_role_informtion.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.create_by
     *
     * @param createBy the value for tbl_shiro_user_role_informtion.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.create_date
     *
     * @return the value of tbl_shiro_user_role_informtion.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.create_date
     *
     * @param createDate the value for tbl_shiro_user_role_informtion.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.update_by
     *
     * @return the value of tbl_shiro_user_role_informtion.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.update_by
     *
     * @param updateBy the value for tbl_shiro_user_role_informtion.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.update_date
     *
     * @return the value of tbl_shiro_user_role_informtion.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.update_date
     *
     * @param updateDate the value for tbl_shiro_user_role_informtion.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shiro_user_role_informtion.id
     *
     * @return the value of tbl_shiro_user_role_informtion.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shiro_user_role_informtion.id
     *
     * @param id the value for tbl_shiro_user_role_informtion.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}