package com.shiro.test.mvc.pojo;

public class WarehouseInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_number
     *
     * @mbggenerated
     */
    private Integer warehouseNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.id
     *
     * @return the value of tbl_warehouse_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.id
     *
     * @param id the value for tbl_warehouse_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_number
     *
     * @return the value of tbl_warehouse_information.warehouse_number
     *
     * @mbggenerated
     */
    public Integer getWarehouseNumber() {
        return warehouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_number
     *
     * @param warehouseNumber the value for tbl_warehouse_information.warehouse_number
     *
     * @mbggenerated
     */
    public void setWarehouseNumber(Integer warehouseNumber) {
        this.warehouseNumber = warehouseNumber;
    }

    @Override
    public String toString() {
        return "WarehouseInformationKey{" +
                "id='" + id + '\'' +
                ", warehouseNumber=" + warehouseNumber +
                '}';
    }
}