package com.shiro.test.mvc.pojo;

import java.util.Date;

public class WarehousingEntryInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehousing_id
     *
     * @mbggenerated
     */
    private String warehousingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehousing_detailed_list_id
     *
     * @mbggenerated
     */
    private String warehousingDetailedListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehousing_detailed_list_code
     *
     * @mbggenerated
     */
    private String warehousingDetailedListCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehousing_no
     *
     * @mbggenerated
     */
    private String warehousingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.commodity_storage_type
     *
     * @mbggenerated
     */
    private Integer commodityStorageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehouse_code
     *
     * @mbggenerated
     */
    private String warehouseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehouse_no
     *
     * @mbggenerated
     */
    private String warehouseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.warehouse_name
     *
     * @mbggenerated
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.shelf_position_id
     *
     * @mbggenerated
     */
    private String shelfPositionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.shelf_position_layer_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionLayerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.shelf_position_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.shelf_position_Row_no
     *
     * @mbggenerated
     */
    private Integer shelfPositionRowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.shelf_position_code
     *
     * @mbggenerated
     */
    private String shelfPositionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehousing_entry_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.id
     *
     * @return the value of tbl_warehousing_entry_information.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.id
     *
     * @param id the value for tbl_warehousing_entry_information.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.create_by
     *
     * @return the value of tbl_warehousing_entry_information.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.create_by
     *
     * @param createBy the value for tbl_warehousing_entry_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.create_date
     *
     * @return the value of tbl_warehousing_entry_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.create_date
     *
     * @param createDate the value for tbl_warehousing_entry_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.update_by
     *
     * @return the value of tbl_warehousing_entry_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.update_by
     *
     * @param updateBy the value for tbl_warehousing_entry_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.update_date
     *
     * @return the value of tbl_warehousing_entry_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.update_date
     *
     * @param updateDate the value for tbl_warehousing_entry_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehousing_id
     *
     * @return the value of tbl_warehousing_entry_information.warehousing_id
     *
     * @mbggenerated
     */
    public String getWarehousingId() {
        return warehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehousing_id
     *
     * @param warehousingId the value for tbl_warehousing_entry_information.warehousing_id
     *
     * @mbggenerated
     */
    public void setWarehousingId(String warehousingId) {
        this.warehousingId = warehousingId == null ? null : warehousingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehousing_detailed_list_id
     *
     * @return the value of tbl_warehousing_entry_information.warehousing_detailed_list_id
     *
     * @mbggenerated
     */
    public String getWarehousingDetailedListId() {
        return warehousingDetailedListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehousing_detailed_list_id
     *
     * @param warehousingDetailedListId the value for tbl_warehousing_entry_information.warehousing_detailed_list_id
     *
     * @mbggenerated
     */
    public void setWarehousingDetailedListId(String warehousingDetailedListId) {
        this.warehousingDetailedListId = warehousingDetailedListId == null ? null : warehousingDetailedListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehousing_detailed_list_code
     *
     * @return the value of tbl_warehousing_entry_information.warehousing_detailed_list_code
     *
     * @mbggenerated
     */
    public String getWarehousingDetailedListCode() {
        return warehousingDetailedListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehousing_detailed_list_code
     *
     * @param warehousingDetailedListCode the value for tbl_warehousing_entry_information.warehousing_detailed_list_code
     *
     * @mbggenerated
     */
    public void setWarehousingDetailedListCode(String warehousingDetailedListCode) {
        this.warehousingDetailedListCode = warehousingDetailedListCode == null ? null : warehousingDetailedListCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehousing_no
     *
     * @return the value of tbl_warehousing_entry_information.warehousing_no
     *
     * @mbggenerated
     */
    public String getWarehousingNo() {
        return warehousingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehousing_no
     *
     * @param warehousingNo the value for tbl_warehousing_entry_information.warehousing_no
     *
     * @mbggenerated
     */
    public void setWarehousingNo(String warehousingNo) {
        this.warehousingNo = warehousingNo == null ? null : warehousingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.commodity_id
     *
     * @return the value of tbl_warehousing_entry_information.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.commodity_id
     *
     * @param commodityId the value for tbl_warehousing_entry_information.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.commodity_code
     *
     * @return the value of tbl_warehousing_entry_information.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.commodity_code
     *
     * @param commodityCode the value for tbl_warehousing_entry_information.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.commodity_storage_type
     *
     * @return the value of tbl_warehousing_entry_information.commodity_storage_type
     *
     * @mbggenerated
     */
    public Integer getCommodityStorageType() {
        return commodityStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.commodity_storage_type
     *
     * @param commodityStorageType the value for tbl_warehousing_entry_information.commodity_storage_type
     *
     * @mbggenerated
     */
    public void setCommodityStorageType(Integer commodityStorageType) {
        this.commodityStorageType = commodityStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehouse_id
     *
     * @return the value of tbl_warehousing_entry_information.warehouse_id
     *
     * @mbggenerated
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehouse_id
     *
     * @param warehouseId the value for tbl_warehousing_entry_information.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehouse_code
     *
     * @return the value of tbl_warehousing_entry_information.warehouse_code
     *
     * @mbggenerated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehouse_code
     *
     * @param warehouseCode the value for tbl_warehousing_entry_information.warehouse_code
     *
     * @mbggenerated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehouse_no
     *
     * @return the value of tbl_warehousing_entry_information.warehouse_no
     *
     * @mbggenerated
     */
    public String getWarehouseNo() {
        return warehouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehouse_no
     *
     * @param warehouseNo the value for tbl_warehousing_entry_information.warehouse_no
     *
     * @mbggenerated
     */
    public void setWarehouseNo(String warehouseNo) {
        this.warehouseNo = warehouseNo == null ? null : warehouseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.warehouse_name
     *
     * @return the value of tbl_warehousing_entry_information.warehouse_name
     *
     * @mbggenerated
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.warehouse_name
     *
     * @param warehouseName the value for tbl_warehousing_entry_information.warehouse_name
     *
     * @mbggenerated
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.shelf_position_id
     *
     * @return the value of tbl_warehousing_entry_information.shelf_position_id
     *
     * @mbggenerated
     */
    public String getShelfPositionId() {
        return shelfPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.shelf_position_id
     *
     * @param shelfPositionId the value for tbl_warehousing_entry_information.shelf_position_id
     *
     * @mbggenerated
     */
    public void setShelfPositionId(String shelfPositionId) {
        this.shelfPositionId = shelfPositionId == null ? null : shelfPositionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.shelf_position_layer_no
     *
     * @return the value of tbl_warehousing_entry_information.shelf_position_layer_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionLayerNo() {
        return shelfPositionLayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.shelf_position_layer_no
     *
     * @param shelfPositionLayerNo the value for tbl_warehousing_entry_information.shelf_position_layer_no
     *
     * @mbggenerated
     */
    public void setShelfPositionLayerNo(Integer shelfPositionLayerNo) {
        this.shelfPositionLayerNo = shelfPositionLayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.shelf_position_no
     *
     * @return the value of tbl_warehousing_entry_information.shelf_position_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionNo() {
        return shelfPositionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.shelf_position_no
     *
     * @param shelfPositionNo the value for tbl_warehousing_entry_information.shelf_position_no
     *
     * @mbggenerated
     */
    public void setShelfPositionNo(Integer shelfPositionNo) {
        this.shelfPositionNo = shelfPositionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.shelf_position_Row_no
     *
     * @return the value of tbl_warehousing_entry_information.shelf_position_Row_no
     *
     * @mbggenerated
     */
    public Integer getShelfPositionRowNo() {
        return shelfPositionRowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.shelf_position_Row_no
     *
     * @param shelfPositionRowNo the value for tbl_warehousing_entry_information.shelf_position_Row_no
     *
     * @mbggenerated
     */
    public void setShelfPositionRowNo(Integer shelfPositionRowNo) {
        this.shelfPositionRowNo = shelfPositionRowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.shelf_position_code
     *
     * @return the value of tbl_warehousing_entry_information.shelf_position_code
     *
     * @mbggenerated
     */
    public String getShelfPositionCode() {
        return shelfPositionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.shelf_position_code
     *
     * @param shelfPositionCode the value for tbl_warehousing_entry_information.shelf_position_code
     *
     * @mbggenerated
     */
    public void setShelfPositionCode(String shelfPositionCode) {
        this.shelfPositionCode = shelfPositionCode == null ? null : shelfPositionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.remark
     *
     * @return the value of tbl_warehousing_entry_information.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.remark
     *
     * @param remark the value for tbl_warehousing_entry_information.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehousing_entry_information.status
     *
     * @return the value of tbl_warehousing_entry_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehousing_entry_information.status
     *
     * @param status the value for tbl_warehousing_entry_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}