package com.shiro.test.mvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class WarehouseInformation extends WarehouseInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.create_date
     *
     * @mbggenerated
     */

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.update_date
     *
     * @mbggenerated
     */

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_name
     *
     * @mbggenerated
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_code
     *
     * @mbggenerated
     */
    private String warehouseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_shelf_position_number
     *
     * @mbggenerated
     */
    private Integer warehouseShelfPositionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_person_in_charge_phone
     *
     * @mbggenerated
     */
    private String warehousePersonInChargePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_person_in_charge_name
     *
     * @mbggenerated
     */
    private String warehousePersonInChargeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_person_in_charge_id
     *
     * @mbggenerated
     */
    private String warehousePersonInChargeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_person_in_charge_code
     *
     * @mbggenerated
     */
    private String warehousePersonInChargeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_person_in_charge
     *
     * @mbggenerated
     */
    private String warehousePersonInCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.opening_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date openingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_type
     *
     * @mbggenerated
     */
    private Integer warehouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.length_unit
     *
     * @mbggenerated
     */
    private String lengthUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.storehouse_bar_code
     *
     * @mbggenerated
     */
    private String storehouseBarCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.area
     *
     * @mbggenerated
     */
    private Double area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.wide
     *
     * @mbggenerated
     */
    private Double wide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.height
     *
     * @mbggenerated
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.commodity_category
     *
     * @mbggenerated
     */
    private String commodityCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_warehouse_information.warehouse_remark
     *
     * @mbggenerated
     */
    private String warehouseRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.create_by
     *
     * @return the value of tbl_warehouse_information.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.create_by
     *
     * @param createBy the value for tbl_warehouse_information.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.create_date
     *
     * @return the value of tbl_warehouse_information.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.create_date
     *
     * @param createDate the value for tbl_warehouse_information.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.update_by
     *
     * @return the value of tbl_warehouse_information.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.update_by
     *
     * @param updateBy the value for tbl_warehouse_information.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.update_date
     *
     * @return the value of tbl_warehouse_information.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.update_date
     *
     * @param updateDate the value for tbl_warehouse_information.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_id
     *
     * @return the value of tbl_warehouse_information.warehouse_id
     *
     * @mbggenerated
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_id
     *
     * @param warehouseId the value for tbl_warehouse_information.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_name
     *
     * @return the value of tbl_warehouse_information.warehouse_name
     *
     * @mbggenerated
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_name
     *
     * @param warehouseName the value for tbl_warehouse_information.warehouse_name
     *
     * @mbggenerated
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_code
     *
     * @return the value of tbl_warehouse_information.warehouse_code
     *
     * @mbggenerated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_code
     *
     * @param warehouseCode the value for tbl_warehouse_information.warehouse_code
     *
     * @mbggenerated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_shelf_position_number
     *
     * @return the value of tbl_warehouse_information.warehouse_shelf_position_number
     *
     * @mbggenerated
     */
    public Integer getWarehouseShelfPositionNumber() {
        return warehouseShelfPositionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_shelf_position_number
     *
     * @param warehouseShelfPositionNumber the value for tbl_warehouse_information.warehouse_shelf_position_number
     *
     * @mbggenerated
     */
    public void setWarehouseShelfPositionNumber(Integer warehouseShelfPositionNumber) {
        this.warehouseShelfPositionNumber = warehouseShelfPositionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_person_in_charge_phone
     *
     * @return the value of tbl_warehouse_information.warehouse_person_in_charge_phone
     *
     * @mbggenerated
     */
    public String getWarehousePersonInChargePhone() {
        return warehousePersonInChargePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_person_in_charge_phone
     *
     * @param warehousePersonInChargePhone the value for tbl_warehouse_information.warehouse_person_in_charge_phone
     *
     * @mbggenerated
     */
    public void setWarehousePersonInChargePhone(String warehousePersonInChargePhone) {
        this.warehousePersonInChargePhone = warehousePersonInChargePhone == null ? null : warehousePersonInChargePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_person_in_charge_name
     *
     * @return the value of tbl_warehouse_information.warehouse_person_in_charge_name
     *
     * @mbggenerated
     */
    public String getWarehousePersonInChargeName() {
        return warehousePersonInChargeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_person_in_charge_name
     *
     * @param warehousePersonInChargeName the value for tbl_warehouse_information.warehouse_person_in_charge_name
     *
     * @mbggenerated
     */
    public void setWarehousePersonInChargeName(String warehousePersonInChargeName) {
        this.warehousePersonInChargeName = warehousePersonInChargeName == null ? null : warehousePersonInChargeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_person_in_charge_id
     *
     * @return the value of tbl_warehouse_information.warehouse_person_in_charge_id
     *
     * @mbggenerated
     */
    public String getWarehousePersonInChargeId() {
        return warehousePersonInChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_person_in_charge_id
     *
     * @param warehousePersonInChargeId the value for tbl_warehouse_information.warehouse_person_in_charge_id
     *
     * @mbggenerated
     */
    public void setWarehousePersonInChargeId(String warehousePersonInChargeId) {
        this.warehousePersonInChargeId = warehousePersonInChargeId == null ? null : warehousePersonInChargeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_person_in_charge_code
     *
     * @return the value of tbl_warehouse_information.warehouse_person_in_charge_code
     *
     * @mbggenerated
     */
    public String getWarehousePersonInChargeCode() {
        return warehousePersonInChargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_person_in_charge_code
     *
     * @param warehousePersonInChargeCode the value for tbl_warehouse_information.warehouse_person_in_charge_code
     *
     * @mbggenerated
     */
    public void setWarehousePersonInChargeCode(String warehousePersonInChargeCode) {
        this.warehousePersonInChargeCode = warehousePersonInChargeCode == null ? null : warehousePersonInChargeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_person_in_charge
     *
     * @return the value of tbl_warehouse_information.warehouse_person_in_charge
     *
     * @mbggenerated
     */
    public String getWarehousePersonInCharge() {
        return warehousePersonInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_person_in_charge
     *
     * @param warehousePersonInCharge the value for tbl_warehouse_information.warehouse_person_in_charge
     *
     * @mbggenerated
     */
    public void setWarehousePersonInCharge(String warehousePersonInCharge) {
        this.warehousePersonInCharge = warehousePersonInCharge == null ? null : warehousePersonInCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.opening_date
     *
     * @return the value of tbl_warehouse_information.opening_date
     *
     * @mbggenerated
     */
    public Date getOpeningDate() {
        return openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.opening_date
     *
     * @param openingDate the value for tbl_warehouse_information.opening_date
     *
     * @mbggenerated
     */
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_type
     *
     * @return the value of tbl_warehouse_information.warehouse_type
     *
     * @mbggenerated
     */
    public Integer getWarehouseType() {
        return warehouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_type
     *
     * @param warehouseType the value for tbl_warehouse_information.warehouse_type
     *
     * @mbggenerated
     */
    public void setWarehouseType(Integer warehouseType) {
        this.warehouseType = warehouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.length_unit
     *
     * @return the value of tbl_warehouse_information.length_unit
     *
     * @mbggenerated
     */
    public String getLengthUnit() {
        return lengthUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.length_unit
     *
     * @param lengthUnit the value for tbl_warehouse_information.length_unit
     *
     * @mbggenerated
     */
    public void setLengthUnit(String lengthUnit) {
        this.lengthUnit = lengthUnit == null ? null : lengthUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.storehouse_bar_code
     *
     * @return the value of tbl_warehouse_information.storehouse_bar_code
     *
     * @mbggenerated
     */
    public String getStorehouseBarCode() {
        return storehouseBarCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.storehouse_bar_code
     *
     * @param storehouseBarCode the value for tbl_warehouse_information.storehouse_bar_code
     *
     * @mbggenerated
     */
    public void setStorehouseBarCode(String storehouseBarCode) {
        this.storehouseBarCode = storehouseBarCode == null ? null : storehouseBarCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.area
     *
     * @return the value of tbl_warehouse_information.area
     *
     * @mbggenerated
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.area
     *
     * @param area the value for tbl_warehouse_information.area
     *
     * @mbggenerated
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.wide
     *
     * @return the value of tbl_warehouse_information.wide
     *
     * @mbggenerated
     */
    public Double getWide() {
        return wide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.wide
     *
     * @param wide the value for tbl_warehouse_information.wide
     *
     * @mbggenerated
     */
    public void setWide(Double wide) {
        this.wide = wide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.height
     *
     * @return the value of tbl_warehouse_information.height
     *
     * @mbggenerated
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.height
     *
     * @param height the value for tbl_warehouse_information.height
     *
     * @mbggenerated
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.commodity_category
     *
     * @return the value of tbl_warehouse_information.commodity_category
     *
     * @mbggenerated
     */
    public String getCommodityCategory() {
        return commodityCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.commodity_category
     *
     * @param commodityCategory the value for tbl_warehouse_information.commodity_category
     *
     * @mbggenerated
     */
    public void setCommodityCategory(String commodityCategory) {
        this.commodityCategory = commodityCategory == null ? null : commodityCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.status
     *
     * @return the value of tbl_warehouse_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.status
     *
     * @param status the value for tbl_warehouse_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_warehouse_information.warehouse_remark
     *
     * @return the value of tbl_warehouse_information.warehouse_remark
     *
     * @mbggenerated
     */
    public String getWarehouseRemark() {
        return warehouseRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_warehouse_information.warehouse_remark
     *
     * @param warehouseRemark the value for tbl_warehouse_information.warehouse_remark
     *
     * @mbggenerated
     */
    public void setWarehouseRemark(String warehouseRemark) {
        this.warehouseRemark = warehouseRemark == null ? null : warehouseRemark.trim();
    }

    @Override
    public String toString() {
        return "WarehouseInformation{" +
                "createBy='" + createBy + '\'' +
                ", createDate=" + createDate +
                ", updateBy='" + updateBy + '\'' +
                ", updateDate=" + updateDate +
                ", warehouseId='" + warehouseId + '\'' +
                ", warehouseName='" + warehouseName + '\'' +
                ", warehouseCode='" + warehouseCode + '\'' +
                ", warehouseShelfPositionNumber=" + warehouseShelfPositionNumber +
                ", warehousePersonInChargePhone='" + warehousePersonInChargePhone + '\'' +
                ", warehousePersonInChargeName='" + warehousePersonInChargeName + '\'' +
                ", warehousePersonInChargeId='" + warehousePersonInChargeId + '\'' +
                ", warehousePersonInChargeCode='" + warehousePersonInChargeCode + '\'' +
                ", warehousePersonInCharge='" + warehousePersonInCharge + '\'' +
                ", openingDate=" + openingDate +
                ", warehouseType=" + warehouseType +
                ", lengthUnit='" + lengthUnit + '\'' +
                ", storehouseBarCode='" + storehouseBarCode + '\'' +
                ", area=" + area +
                ", wide=" + wide +
                ", height=" + height +
                ", commodityCategory='" + commodityCategory + '\'' +
                ", status=" + status +
                ", warehouseRemark='" + warehouseRemark + '\'' +
                '}';
    }
}