package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.CommodityClassInformation;
import com.shiro.test.mvc.pojo.CommodityClassInformationKey;

public interface CommodityClassInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_class_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CommodityClassInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_class_information
     *
     * @mbggenerated
     */
    int insert(CommodityClassInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_class_information
     *
     * @mbggenerated
     */
    int insertSelective(CommodityClassInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_class_information
     *
     * @mbggenerated
     */
    CommodityClassInformation selectByPrimaryKey(CommodityClassInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_class_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommodityClassInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_class_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityClassInformation record);

    CommodityClassInformation  selectByPrimaryCode(CommodityClassInformation commodityClassInformation);
}