package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.CommodityDetailedListBean;

import java.util.List;

public interface CommodityDetailedListBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_detailed_list_bean
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_detailed_list_bean
     *
     * @mbggenerated
     */
    int insert(CommodityDetailedListBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_detailed_list_bean
     *
     * @mbggenerated
     */
    int insertSelective(CommodityDetailedListBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_detailed_list_bean
     *
     * @mbggenerated
     */
    CommodityDetailedListBean selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_detailed_list_bean
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommodityDetailedListBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_commodity_detailed_list_bean
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityDetailedListBean record);

    int AddCommodityDetailedListBean_Batch(List<CommodityDetailedListBean> listBeans);

    int deleteByDetailedListIdKey(String DetailedListId);

    List<CommodityDetailedListBean> QueryCommodityDetailedListBeanGroupByCommodityId();
}