package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.DetailedListInformation;

import java.util.List;
import java.util.Map;

public interface DetailedListInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_detailed_list_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_detailed_list_information
     *
     * @mbggenerated
     */
    int insert(DetailedListInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_detailed_list_information
     *
     * @mbggenerated
     */
    int insertSelective(DetailedListInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_detailed_list_information
     *
     * @mbggenerated
     */
    DetailedListInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_detailed_list_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DetailedListInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_detailed_list_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DetailedListInformation record);

    List<DetailedListInformation> QureyAllDetailedListInformation(Map map);

    Integer SelectWarehousingOutOfStackCount(Map map);

    Integer SelectDetailedListTypeCount(Map map);

    Integer SelectDetailedListApplicantIdCount(Map map);
}