package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.MenuInformation;

import java.util.List;

public interface MenuInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_menu_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_menu_information
     *
     * @mbggenerated
     */
    int insert(MenuInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_menu_information
     *
     * @mbggenerated
     */
    int insertSelective(MenuInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_menu_information
     *
     * @mbggenerated
     */
    MenuInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_menu_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MenuInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_menu_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuInformation record);

    List<MenuInformation> getAllMenuInformation();
}