package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.OutOfStock;

import java.util.List;

public interface OutOfStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_out_of_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_out_of_stock
     *
     * @mbggenerated
     */
    int insert(OutOfStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_out_of_stock
     *
     * @mbggenerated
     */
    int insertSelective(OutOfStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_out_of_stock
     *
     * @mbggenerated
     */
    OutOfStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_out_of_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutOfStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_out_of_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutOfStock record);

    List<OutOfStock> QureyAllOutOfStock();
}