package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.RoleMenuInformation;

import java.util.List;

public interface RoleMenuInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_role_menu_information
     *
     * @mbggenerated
     */
    int insert(RoleMenuInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_role_menu_information
     *
     * @mbggenerated
     */
    int insertSelective(RoleMenuInformation record);

    List<RoleMenuInformation> FindRoleMenuList();

    int deleteRoleMenuInformation(String roleId);

    List<String> getMenuIdByRoleId(String roleId);

    int FindCountByRoleID(String roleId);

    int AddRoleMenuInformation_Batch(List<RoleMenuInformation> list);
}