package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.base.Bean.PositionCommodityCountInformationBean;
import com.shiro.test.mvc.pojo.ShelfPositionInformation;
import com.shiro.test.mvc.pojo.ShelfPositionInformationKey;

import java.util.List;
import java.util.Map;

public interface ShelfPositionInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shelf_position_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ShelfPositionInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shelf_position_information
     *
     * @mbggenerated
     */
    int insert(ShelfPositionInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shelf_position_information
     *
     * @mbggenerated
     */
    int insertSelective(ShelfPositionInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shelf_position_information
     *
     * @mbggenerated
     */
    ShelfPositionInformation selectByPrimaryKey(ShelfPositionInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shelf_position_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShelfPositionInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shelf_position_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShelfPositionInformation record);

    List<ShelfPositionInformation> QureyAllShelfPositionInformation();

    int  AddShelfPositionInformation_Batch(List<ShelfPositionInformation> list);

    List<ShelfPositionInformation> Find_LikeQureyAllShelfPositionInformation(ShelfPositionInformation shelfPositionInformation);

    Integer FindShelfPositionNumber(Map map);

    Integer updateIsItEmptyBatch(List<ShelfPositionInformation> shelfPositionInformations);

    List<ShelfPositionInformation>  Find_ShelfPositionInformation_SpecifiedQuantity(Map map);

    Integer updateIsItEmptyDetermineWarehousing(Map map);

    Integer updateCancelApplicationFormStatusChange_Warehousing(Map map);

    List<PositionCommodityCountInformationBean> SelectPositionCommodityId();

    Integer SelectPositionCommodityIdCount(String CommodityId);

    Integer  updateCancelApplicationFormStatusChange_OutOfStock(Map map);

    /*按出库单ID查询*/
    List<ShelfPositionInformation>   selectShelfPositionDetailedListOutOfStockId(String detailedListOutOfStockId);

    /*架位使用次数加1*/
    int updateShelfPositionUsageRecord(List<ShelfPositionInformation> shelfPositionInformations);

    /*查询状态数量*/
    Integer Find_ShelfPositionIsItEmpty(Integer isItEmpty);
}