package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.SuppliersInformation;
import com.shiro.test.mvc.pojo.SuppliersInformationKey;

import java.util.List;

public interface SuppliersInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SuppliersInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_information
     *
     * @mbggenerated
     */
    int insert(SuppliersInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_information
     *
     * @mbggenerated
     */
    int insertSelective(SuppliersInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_information
     *
     * @mbggenerated
     */
    SuppliersInformation selectByPrimaryKey(SuppliersInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SuppliersInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SuppliersInformation record);

    List<SuppliersInformation> queryAllSupplier();

    List<SuppliersInformation> findLikeSupplier( SuppliersInformation suppliersInformation);

    SuppliersInformation selectByIfKey(SuppliersInformationKey key);

}