package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.testTime;

import java.util.List;

public interface testTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_time
     *
     * @mbggenerated
     */
    int insert(testTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_time
     *
     * @mbggenerated
     */
    int insertSelective(testTime record);

    List<testTime> queryTime();

}