package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.UserRoleInformation;

public interface UserRoleInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_role_informtion
     *
     * @mbggenerated
     */
    int insert(UserRoleInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_role_informtion
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleInformation record);

    String getUserRoleIds(String userId);

    Integer deleteUserRoleByUserId(String userId);
}