package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.RoleInformation;
import com.shiro.test.mvc.pojo.UserInformation;

import java.util.List;
import java.util.Map;

public interface UserInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_information
     *
     * @mbggenerated
     */
    int insert(UserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_information
     *
     * @mbggenerated
     */
    int insertSelective(UserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_information
     *
     * @mbggenerated
     */
    UserInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shiro_user_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInformation record);

    UserInformation getUserByEmail(String email);

    List<UserInformation> getUserList();

    List<UserInformation> findLikeUserInformation(UserInformation userInformation);

    RoleInformation getRoleByRoleID(String roleId);

    Integer updataPassword(Map map);

    UserInformation getUser(Map map);

    Integer  addUser(UserInformation user);
}