package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.WarehousingEntryInformation;

import java.util.List;

public interface WarehousingEntryInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehousing_entry_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehousing_entry_information
     *
     * @mbggenerated
     */
    int insert(WarehousingEntryInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehousing_entry_information
     *
     * @mbggenerated
     */
    int insertSelective(WarehousingEntryInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehousing_entry_information
     *
     * @mbggenerated
     */
    WarehousingEntryInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehousing_entry_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WarehousingEntryInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehousing_entry_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WarehousingEntryInformation record);

    List<WarehousingEntryInformation> QureyAllWarehousingEntryInformation();
}