package com.shiro.test.mvc.dao;

import com.shiro.test.mvc.pojo.WarehouseInformation;

import java.util.List;

public interface WarehouseInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehouse_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehouse_information
     *
     * @mbggenerated
     */
    int insert(WarehouseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehouse_information
     *
     * @mbggenerated
     */
    int insertSelective(WarehouseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehouse_information
     *
     * @mbggenerated
     */
    WarehouseInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehouse_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WarehouseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_warehouse_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WarehouseInformation record);


    List<WarehouseInformation> QureyAllWarehouseInformation();

    List<WarehouseInformation> find_likeWarehouseInformationList(WarehouseInformation record);

    WarehouseInformation selectByWarehouseId(String warehouseId);

    WarehouseInformation selectByWarehouseNumber(Integer WarehouseNumber);
}